const cssProperties = {
  'accent-color': { alias: 'ac', type: 'color', syntax: '<color>', compiler: (v) => v, values: [] },
  'align-content': {
    alias: 'ac',
    type: 'layout',
    syntax:
      'normal | baseline | stretch | center | flex-start | flex-end | space-between | space-around | space-evenly',
    compiler: (v) => v,
    values: [
      'normal:n',
      'baseline:b',
      'stretch:s',
      'center:c',
      'flex-start:fs',
      'flex-end:fe',
      'space-between:sb',
      'space-around:sa',
      'space-evenly:se',
    ],
  },
  'align-items': {
    alias: 'ai',
    type: 'layout',
    syntax: 'normal | stretch | baseline | center | flex-start | flex-end | self-start | self-end',
    compiler: (v) => v,
    values: ['normal:n', 'stretch:s', 'baseline:b', 'center:c', 'flex-start:fs', 'flex-end:fe'],
  },
  'align-self': {
    alias: 'as',
    type: 'layout',
    syntax: 'auto | normal | stretch | baseline | center | flex-start | flex-end',
    compiler: (v) => v,
    values: ['auto:a', 'normal:n', 'stretch:s', 'baseline:b', 'center:c'],
  },
  all: {
    alias: 'all',
    type: 'reset',
    syntax: 'initial | inherit | revert | unset',
    compiler: (v) => v,
    values: ['initial:i', 'inherit:ih', 'revert:r', 'unset:u'],
  },
  animation: {
    alias: 'anim',
    type: 'motion',
    syntax: '<time> <easing-function>? <time>? fill-mode? iteration-count? direction? play-state? name?',
    compiler: (v) => v,
    values: [],
  },
  'animation-delay': { alias: 'ad', type: 'motion', syntax: '<time>#', compiler: (v) => v, values: [] },
  'animation-direction': {
    alias: 'adir',
    type: 'motion',
    syntax: 'normal | reverse | alternate | alternate-reverse',
    compiler: (v) => v,
    values: ['normal:n', 'reverse:r', 'alternate:a', 'alternate-reverse:ar'],
  },
  'animation-duration': { alias: 'adur', type: 'motion', syntax: '<time>#', compiler: (v) => v, values: [] },
  'animation-fill-mode': {
    alias: 'afm',
    type: 'motion',
    syntax: 'none | forwards | backwards | both',
    compiler: (v) => v,
    values: ['none:n', 'forwards:f', 'backwards:b', 'both:bo'],
  },
  'animation-iteration-count': {
    alias: 'aic',
    type: 'motion',
    syntax: 'infinite | <number>',
    compiler: (v) => v,
    values: ['infinite:i'],
  },
  'animation-name': { alias: 'an', type: 'motion', syntax: 'none | <keyframe-name>#', compiler: (v) => v, values: [] },
  'animation-play-state': {
    alias: 'aps',
    type: 'motion',
    syntax: 'running | paused',
    compiler: (v) => v,
    values: ['running:r', 'paused:p'],
  },
  'animation-timeline': {
    alias: 'atl',
    type: 'motion',
    syntax: 'auto | none | <timeline-range-name>',
    compiler: (v) => v,
    values: ['auto:a', 'none:n'],
  },
  'animation-timing-function': {
    alias: 'atf',
    type: 'motion',
    syntax: 'ease | linear | ease-in | ease-out | ease-in-out | cubic-bezier()',
    compiler: (v) => v,
    values: ['ease:e', 'linear:l', 'ease-in:ei', 'ease-out:eo'],
  },
  appearance: { alias: 'app', type: 'ui', syntax: 'none | auto', compiler: (v) => v, values: ['none:n', 'auto:a'] },
  'aspect-ratio': { alias: 'ar', type: 'layout', syntax: '<number> | auto', compiler: (v) => v, values: ['auto:a'] },
  'backdrop-filter': {
    alias: 'bf',
    type: 'effect',
    syntax: 'none | <filter-function-list>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'backface-visibility': {
    alias: 'bfv',
    type: '3d',
    syntax: 'visible | hidden',
    compiler: (v) => v,
    values: ['visible:v', 'hidden:h'],
  },
  background: { alias: 'bg', type: 'visual', syntax: '<bg-layer>#', compiler: (v) => v, values: [] },
  'background-attachment': {
    alias: 'bga',
    type: 'visual',
    syntax: 'scroll | fixed | local',
    compiler: (v) => v,
    values: ['scroll:s', 'fixed:f', 'local:l'],
  },
  'background-blend-mode': { alias: 'bgbm', type: 'visual', syntax: '<blend-mode>#', compiler: (v) => v, values: [] },
  'background-clip': {
    alias: 'bgc',
    type: 'visual',
    syntax: 'border-box | padding-box | content-box',
    compiler: (v) => v,
    values: ['border-box:bb', 'padding-box:pb', 'content-box:cb'],
  },
  'background-color': { alias: 'bc', type: 'color', syntax: '<color>', compiler: (v) => v, values: [] },
  'background-image': {
    alias: 'bgi',
    type: 'visual',
    syntax: 'none | <image>#',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'background-origin': {
    alias: 'bgo',
    type: 'visual',
    syntax: 'padding-box | border-box | content-box',
    compiler: (v) => v,
    values: ['padding-box:pb', 'border-box:bb', 'content-box:cb'],
  },
  'background-position': {
    alias: 'bgp',
    type: 'visual',
    syntax: '<position>#',
    compiler: (v) => v,
    values: ['center:c', 'top:t', 'bottom:b', 'left:l', 'right:r'],
  },
  'background-position-x': {
    alias: 'bgpx',
    type: 'visual',
    syntax: 'center | left | right | <length-percentage>',
    compiler: (v) => v,
    values: ['center:c', 'left:l', 'right:r'],
  },
  'background-position-y': {
    alias: 'bgpy',
    type: 'visual',
    syntax: 'center | top | bottom | <length-percentage>',
    compiler: (v) => v,
    values: ['center:c', 'top:t', 'bottom:b'],
  },
  'background-repeat': {
    alias: 'bgr',
    type: 'visual',
    syntax: 'repeat | space | round | no-repeat',
    compiler: (v) => v,
    values: ['repeat:r', 'no-repeat:nr', 'space:s', 'round:ro'],
  },
  'background-size': {
    alias: 'bgs',
    type: 'visual',
    syntax: '<length-percentage> | auto | cover | contain',
    compiler: (v) => v,
    values: ['auto:a', 'cover:c', 'contain:cn'],
  },
  'baseline-shift': {
    alias: 'bs',
    type: 'typography',
    syntax: 'baseline | sub | super | <percentage> | <length>',
    compiler: (v) => v,
    values: ['baseline:b', 'sub:s', 'super:sp'],
  },
  'block-size': {
    alias: 'bsz',
    type: 'size',
    syntax: 'auto | <length-percentage> | min-content | max-content',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  border: {
    alias: 'b',
    type: 'border',
    syntax: '<line-width> || <line-style> || <color>',
    compiler: (v) => v,
    values: [],
  },
  'border-block': {
    alias: 'bb',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-block-color': { alias: 'bbc', type: 'border', syntax: '<color>{1,2}', compiler: (v) => v, values: [] },
  'border-block-end': {
    alias: 'bbe',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-block-end-color': { alias: 'bbec', type: 'border', syntax: '<color>', compiler: (v) => v, values: [] },
  'border-block-end-style': {
    alias: 'bbes',
    type: 'border',
    syntax: "<'border-top-style'>",
    compiler: (v) => v,
    values: [],
  },
  'border-block-end-width': {
    alias: 'bbew',
    type: 'border',
    syntax: "<'border-top-width'>",
    compiler: (v) => v,
    values: [],
  },
  'border-block-start': {
    alias: 'bbs',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-block-start-color': { alias: 'bbsc', type: 'border', syntax: '<color>', compiler: (v) => v, values: [] },
  'border-block-start-style': {
    alias: 'bbss',
    type: 'border',
    syntax: "<'border-top-style'>",
    compiler: (v) => v,
    values: [],
  },
  'border-block-start-width': {
    alias: 'bbsw',
    type: 'border',
    syntax: "<'border-top-width'>",
    compiler: (v) => v,
    values: [],
  },
  'border-block-style': {
    alias: 'bbs',
    type: 'border',
    syntax: "<'border-top-style'>{1,2}",
    compiler: (v) => v,
    values: [],
  },
  'border-block-width': {
    alias: 'bbw',
    type: 'border',
    syntax: "<'border-top-width'>{1,2}",
    compiler: (v) => v,
    values: [],
  },
  'border-bottom': {
    alias: 'bb',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-bottom-color': { alias: 'bbc', type: 'border', syntax: '<color>', compiler: (v) => v, values: [] },
  'border-bottom-left-radius': {
    alias: 'bblr',
    type: 'border',
    syntax: '<length-percentage>{1,2}',
    compiler: (v) => v,
    values: [],
  },
  'border-bottom-right-radius': {
    alias: 'bbrr',
    type: 'border',
    syntax: '<length-percentage>{1,2}',
    compiler: (v) => v,
    values: [],
  },
  'border-bottom-style': {
    alias: 'bbs',
    type: 'border',
    syntax: "<'border-top-style'>",
    compiler: (v) => v,
    values: [],
  },
  'border-bottom-width': {
    alias: 'bbw',
    type: 'border',
    syntax: "<'border-top-width'>",
    compiler: (v) => v,
    values: [],
  },
  'border-collapse': {
    alias: 'bc',
    type: 'table',
    syntax: 'collapse | separate',
    compiler: (v) => v,
    values: ['collapse:c', 'separate:s'],
  },
  'border-color': { alias: 'bc', type: 'border', syntax: '<color>{1,4}', compiler: (v) => v, values: [] },
  'border-end-end-radius': {
    alias: 'beer',
    type: 'border',
    syntax: '<length-percentage>{1,2}',
    compiler: (v) => v,
    values: [],
  },
  'border-end-start-radius': {
    alias: 'besr',
    type: 'border',
    syntax: '<length-percentage>{1,2}',
    compiler: (v) => v,
    values: [],
  },
  'border-image': {
    alias: 'bi',
    type: 'border',
    syntax:
      "<'border-image-source'> || <'border-image-slice'> [/ <'border-image-width'>]? [/ <'border-image-outset'>]? || <'border-image-repeat'>",
    compiler: (v) => v,
    values: [],
  },
  'border-image-outset': {
    alias: 'bio',
    type: 'border',
    syntax: '[<length> | <number>]{1,4}',
    compiler: (v) => v,
    values: [],
  },
  'border-image-repeat': {
    alias: 'bir',
    type: 'border',
    syntax: 'stretch | repeat | round | space',
    compiler: (v) => v,
    values: ['stretch:s', 'repeat:r', 'round:ro', 'space:sp'],
  },
  'border-image-slice': {
    alias: 'bis',
    type: 'border',
    syntax: '<number-percentage>{1,4} && fill?',
    compiler: (v) => v,
    values: [],
  },
  'border-image-source': {
    alias: 'bisrc',
    type: 'border',
    syntax: 'none | <image>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'border-image-width': {
    alias: 'biw',
    type: 'border',
    syntax: '[<length-percentage> | <number> | auto]{1,4}',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'border-inline': {
    alias: 'bi',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-inline-color': { alias: 'bic', type: 'border', syntax: '<color>{1,2}', compiler: (v) => v, values: [] },
  'border-inline-end': {
    alias: 'bie',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-inline-end-color': { alias: 'biec', type: 'border', syntax: '<color>', compiler: (v) => v, values: [] },
  'border-inline-end-style': {
    alias: 'bies',
    type: 'border',
    syntax: "<'border-top-style'>",
    compiler: (v) => v,
    values: [],
  },
  'border-inline-end-width': {
    alias: 'biew',
    type: 'border',
    syntax: "<'border-top-width'>",
    compiler: (v) => v,
    values: [],
  },
  'border-inline-start': {
    alias: 'bis',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-inline-start-color': { alias: 'bisc', type: 'border', syntax: '<color>', compiler: (v) => v, values: [] },
  'border-inline-start-style': {
    alias: 'biss',
    type: 'border',
    syntax: "<'border-top-style'>",
    compiler: (v) => v,
    values: [],
  },
  'border-inline-start-width': {
    alias: 'bisw',
    type: 'border',
    syntax: "<'border-top-width'>",
    compiler: (v) => v,
    values: [],
  },
  'border-inline-style': {
    alias: 'bis',
    type: 'border',
    syntax: "<'border-top-style'>{1,2}",
    compiler: (v) => v,
    values: [],
  },
  'border-inline-width': {
    alias: 'biw',
    type: 'border',
    syntax: "<'border-top-width'>{1,2}",
    compiler: (v) => v,
    values: [],
  },
  'border-left': {
    alias: 'bl',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-left-color': { alias: 'blc', type: 'border', syntax: '<color>', compiler: (v) => v, values: [] },
  'border-left-style': { alias: 'bls', type: 'border', syntax: "<'border-top-style'>", compiler: (v) => v, values: [] },
  'border-left-width': { alias: 'blw', type: 'border', syntax: "<'border-top-width'>", compiler: (v) => v, values: [] },
  'border-radius': {
    alias: 'br',
    type: 'border',
    syntax: '<length-percentage>{1,4} [/ <length-percentage>{1,4}]?',
    compiler: (v) => v,
    values: [],
  },
  'border-right': {
    alias: 'br',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-right-color': { alias: 'brc', type: 'border', syntax: '<color>', compiler: (v) => v, values: [] },
  'border-right-style': {
    alias: 'brs',
    type: 'border',
    syntax: "<'border-top-style'>",
    compiler: (v) => v,
    values: [],
  },
  'border-right-width': {
    alias: 'brw',
    type: 'border',
    syntax: "<'border-top-width'>",
    compiler: (v) => v,
    values: [],
  },
  'border-spacing': { alias: 'bs', type: 'table', syntax: '<length> [<length>]?', compiler: (v) => v, values: [] },
  'border-start-end-radius': {
    alias: 'bser',
    type: 'border',
    syntax: '<length-percentage>{1,2}',
    compiler: (v) => v,
    values: [],
  },
  'border-start-start-radius': {
    alias: 'bssr',
    type: 'border',
    syntax: '<length-percentage>{1,2}',
    compiler: (v) => v,
    values: [],
  },
  'border-style': { alias: 'bs', type: 'border', syntax: "<'border-top-style'>{1,4}", compiler: (v) => v, values: [] },
  'border-top': {
    alias: 'bt',
    type: 'border',
    syntax: "<'border-top-width'> || <'border-top-style'> || <color>",
    compiler: (v) => v,
    values: [],
  },
  'border-top-color': { alias: 'btc', type: 'border', syntax: '<color>', compiler: (v) => v, values: [] },
  'border-top-left-radius': {
    alias: 'btlr',
    type: 'border',
    syntax: '<length-percentage>{1,2}',
    compiler: (v) => v,
    values: [],
  },
  'border-top-right-radius': {
    alias: 'btrr',
    type: 'border',
    syntax: '<length-percentage>{1,2}',
    compiler: (v) => v,
    values: [],
  },
  'border-top-style': { alias: 'bts', type: 'border', syntax: "<'border-style'>", compiler: (v) => v, values: [] },
  'border-top-width': { alias: 'btw', type: 'border', syntax: "<'border-width'>", compiler: (v) => v, values: [] },
  'border-width': { alias: 'bw', type: 'border', syntax: "<'border-top-width'>{1,4}", compiler: (v) => v, values: [] },
  bottom: {
    alias: 'b',
    type: 'position',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'box-decoration-break': {
    alias: 'bdb',
    type: 'layout',
    syntax: 'slice | clone',
    compiler: (v) => v,
    values: ['slice:s', 'clone:c'],
  },
  'box-shadow': { alias: 'bs', type: 'visual', syntax: 'none | <shadow>#', compiler: (v) => v, values: ['none:n'] },
  'box-sizing': {
    alias: 'bsz',
    type: 'layout',
    syntax: 'content-box | border-box',
    compiler: (v) => v,
    values: ['content-box:cb', 'border-box:bb'],
  },
  'break-after': {
    alias: 'ba',
    type: 'layout',
    syntax:
      'auto | avoid | always | all | avoid-page | page | left | right | avoid-column | column | avoid-region | region',
    compiler: (v) => v,
    values: ['auto:a', 'avoid:av'],
  },
  'break-before': {
    alias: 'bb',
    type: 'layout',
    syntax:
      'auto | avoid | always | all | avoid-page | page | left | right | avoid-column | column | avoid-region | region',
    compiler: (v) => v,
    values: ['auto:a', 'avoid:av'],
  },
  'break-inside': {
    alias: 'bi',
    type: 'layout',
    syntax: 'auto | avoid | avoid-page | avoid-column | avoid-region',
    compiler: (v) => v,
    values: ['auto:a', 'avoid:av'],
  },
  'caption-side': {
    alias: 'cs',
    type: 'table',
    syntax: 'top | bottom | block-start | block-end | inline-start | inline-end',
    compiler: (v) => v,
    values: ['top:t', 'bottom:b'],
  },
  'caret-color': { alias: 'cc', type: 'color', syntax: 'auto | <color>', compiler: (v) => v, values: ['auto:a'] },
  'caret-shape': {
    alias: 'csh',
    type: 'ui',
    syntax: 'auto | bar | block | underscore',
    compiler: (v) => v,
    values: ['auto:a', 'bar:b', 'block:bl'],
  },
  clear: {
    alias: 'c',
    type: 'layout',
    syntax: 'none | left | right | both | inline-start | inline-end',
    compiler: (v) => v,
    values: ['none:n', 'left:l', 'right:r', 'both:b'],
  },
  clip: { alias: 'clip', type: 'layout', syntax: '<shape> | auto', compiler: (v) => v, values: ['auto:a'] },
  'clip-path': {
    alias: 'cp',
    type: 'layout',
    syntax: '<clip-source> | [<basic-shape> || <geometry-box>] | none',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'clip-rule': {
    alias: 'cr',
    type: 'layout',
    syntax: 'nonzero | evenodd',
    compiler: (v) => v,
    values: ['nonzero:nz', 'evenodd:eo'],
  },
  color: { alias: 'c', type: 'color', syntax: '<color>', compiler: (v) => v, values: [] },
  'color-interpolation': {
    alias: 'ci',
    type: 'color',
    syntax: 'auto | sRGB | linearRGB',
    compiler: (v) => v,
    values: ['auto:a', 'sRGB', 'linearRGB'],
  },
  'color-interpolation-filters': {
    alias: 'cif',
    type: 'color',
    syntax: 'auto | sRGB | linearRGB',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'color-rendering': {
    alias: 'cr',
    type: 'color',
    syntax: 'auto | optimizeSpeed | optimizeQuality',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'color-scheme': {
    alias: 'cs',
    type: 'color',
    syntax: 'normal | [light | dark | <custom-ident>]+',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'column-count': {
    alias: 'cc',
    type: 'layout',
    syntax: '<integer> | auto',
    compiler: (v) => parseInt(v),
    values: ['auto:a'],
  },
  'column-fill': {
    alias: 'cf',
    type: 'layout',
    syntax: 'auto | balance | balance-all',
    compiler: (v) => v,
    values: ['auto:a', 'balance:b'],
  },
  'column-gap': {
    alias: 'cg',
    type: 'layout',
    syntax: 'normal | <length-percentage>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'column-rule': {
    alias: 'cr',
    type: 'layout',
    syntax: "<'column-rule-width'> || <'column-rule-style'> || <'column-rule-color'>",
    compiler: (v) => v,
    values: [],
  },
  'column-rule-color': { alias: 'crc', type: 'layout', syntax: '<color>', compiler: (v) => v, values: [] },
  'column-rule-style': { alias: 'crs', type: 'layout', syntax: "<'border-style'>", compiler: (v) => v, values: [] },
  'column-rule-width': { alias: 'crw', type: 'layout', syntax: "<'border-width'>", compiler: (v) => v, values: [] },
  'column-span': { alias: 'cs', type: 'layout', syntax: 'none | all', compiler: (v) => v, values: ['none:n', 'all:a'] },
  'column-width': { alias: 'cw', type: 'layout', syntax: '<length> | auto', compiler: (v) => v, values: ['auto:a'] },
  columns: {
    alias: 'cols',
    type: 'layout',
    syntax: "<'column-width'> || <'column-count'>",
    compiler: (v) => v,
    values: [],
  },
  contain: {
    alias: 'contain',
    type: 'layout',
    syntax: 'none | strict | content | [size || layout || style || paint]',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'contain-intrinsic-block-size': {
    alias: 'cibs',
    type: 'layout',
    syntax: 'none | <length>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'contain-intrinsic-height': {
    alias: 'cih',
    type: 'layout',
    syntax: 'none | <length>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'contain-intrinsic-inline-size': {
    alias: 'ciis',
    type: 'layout',
    syntax: 'none | <length>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'contain-intrinsic-size': {
    alias: 'cis',
    type: 'layout',
    syntax: '[none | <length>]{1,2}',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'contain-intrinsic-width': {
    alias: 'ciw',
    type: 'layout',
    syntax: 'none | <length>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  content: {
    alias: 'content',
    type: 'layout',
    syntax: 'normal | none | [<string> | counter() | counters() | attr() | url() | image-set()]+',
    compiler: (v) => v,
    values: ['normal:n', 'none:n'],
  },
  'content-visibility': {
    alias: 'cv',
    type: 'layout',
    syntax: 'visible | auto | hidden',
    compiler: (v) => v,
    values: ['visible:v', 'auto:a', 'hidden:h'],
  },
  'counter-increment': {
    alias: 'ci',
    type: 'layout',
    syntax: '[<custom-ident> <integer>?]+ | none',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'counter-reset': {
    alias: 'cr',
    type: 'layout',
    syntax: '[<custom-ident> <integer>?]+ | none',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'counter-set': {
    alias: 'cs',
    type: 'layout',
    syntax: '[<custom-ident> <integer>?]+ | none',
    compiler: (v) => v,
    values: ['none:n'],
  },
  cursor: {
    alias: 'cursor',
    type: 'ui',
    syntax:
      '[<url> [<x> <y>]?,]* [auto | default | none | context-menu | help | pointer | progress | wait | cell | crosshair | text | vertical-text | alias | copy | move | no-drop | not-allowed | grab | grabbing | e-resize | n-resize | ne-resize | nw-resize | s-resize | se-resize | sw-resize | w-resize | ew-resize | ns-resize | nesw-resize | nwse-resize | col-resize | row-resize | all-scroll | zoom-in | zoom-out]',
    compiler: (v) => v,
    values: ['auto:a', 'pointer:p', 'default:d', 'none:n'],
  },
  cx: { alias: 'cx', type: 'svg', syntax: '<length> | <percentage>', compiler: (v) => v, values: [] },
  cy: { alias: 'cy', type: 'svg', syntax: '<length> | <percentage>', compiler: (v) => v, values: [] },
  d: { alias: 'd', type: 'svg', syntax: 'none | <path-data>', compiler: (v) => v, values: ['none:n'] },
  direction: { alias: 'dir', type: 'layout', syntax: 'ltr | rtl', compiler: (v) => v, values: ['ltr', 'rtl'] },
  display: {
    alias: 'd',
    type: 'layout',
    syntax:
      '[<display-outside> || <display-inside>] | <display-listitem> | <display-internal> | <display-box> | <display-legacy>',
    compiler: (v) => v,
    values: ['none:n', 'block:b', 'inline:i', 'flex:f', 'grid:g', 'inline-flex:if', 'inline-grid:ig'],
  },
  'dominant-baseline': {
    alias: 'db',
    type: 'typography',
    syntax: 'auto | text-bottom | alphabetic | ideographic | middle | central | mathematical | hanging | text-top',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'empty-cells': {
    alias: 'ec',
    type: 'table',
    syntax: 'show | hide',
    compiler: (v) => v,
    values: ['show:s', 'hide:h'],
  },
  fill: { alias: 'fill', type: 'paint', syntax: '<paint>', compiler: (v) => v, values: [] },
  'fill-opacity': { alias: 'fo', type: 'paint', syntax: '<number-percentage>', compiler: (v) => v, values: [] },
  'fill-rule': {
    alias: 'fr',
    type: 'svg',
    syntax: 'nonzero | evenodd',
    compiler: (v) => v,
    values: ['nonzero:nz', 'evenodd:eo'],
  },
  filter: {
    alias: 'filter',
    type: 'effect',
    syntax: 'none | <filter-function-list>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  flex: {
    alias: 'flex',
    type: 'layout',
    syntax: "none | [<'flex-grow'> <'flex-shrink'>? || <'flex-basis'>]",
    compiler: (v) => v,
    values: ['none:n'],
  },
  'flex-basis': {
    alias: 'fb',
    type: 'layout',
    syntax: 'content | <length-percentage> | auto',
    compiler: (v) => v,
    values: ['auto:a', 'content:c'],
  },
  'flex-direction': {
    alias: 'fd',
    type: 'layout',
    syntax: 'row | row-reverse | column | column-reverse',
    compiler: (v) => v,
    values: ['row:r', 'row-reverse:rr', 'column:c', 'column-reverse:cr'],
  },
  'flex-flow': {
    alias: 'ff',
    type: 'layout',
    syntax: "<'flex-direction'> || <'flex-wrap'>",
    compiler: (v) => v,
    values: [],
  },
  'flex-grow': { alias: 'fg', type: 'layout', syntax: '<number>', compiler: (v) => parseFloat(v), values: [] },
  'flex-shrink': { alias: 'fs', type: 'layout', syntax: '<number>', compiler: (v) => parseFloat(v), values: [] },
  'flex-wrap': {
    alias: 'fw',
    type: 'layout',
    syntax: 'nowrap | wrap | wrap-reverse',
    compiler: (v) => v,
    values: ['nowrap:n', 'wrap:w', 'wrap-reverse:wr'],
  },
  float: {
    alias: 'fl',
    type: 'layout',
    syntax: 'none | left | right | inline-start | inline-end',
    compiler: (v) => v,
    values: ['none:n', 'left:l', 'right:r'],
  },
  'flood-color': { alias: 'fc', type: 'color', syntax: '<color>', compiler: (v) => v, values: [] },
  'flood-opacity': { alias: 'fo', type: 'color', syntax: '<number-percentage>', compiler: (v) => v, values: [] },
  font: {
    alias: 'f',
    type: 'typography',
    syntax:
      "[<'font-style'> || <font-variant-css21> || <'font-weight'> || <'font-stretch'>]? <'font-size'> [/ <'line-height'>]? <'font-family'> | caption | icon | menu | message-box | small-caption | status-bar",
    compiler: (v) => v,
    values: [],
  },
  'font-family': {
    alias: 'ff',
    type: 'typography',
    syntax: '[<family-name> | <generic-family>]#',
    compiler: (v) => v,
    values: ['serif:s', 'sans-serif:ss', 'monospace:m'],
  },
  'font-feature-settings': {
    alias: 'ffs',
    type: 'typography',
    syntax: 'normal | <feature-tag-value>#',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-kerning': {
    alias: 'fk',
    type: 'typography',
    syntax: 'auto | normal | none',
    compiler: (v) => v,
    values: ['auto:a', 'normal:n', 'none:n'],
  },
  'font-language-override': {
    alias: 'flo',
    type: 'typography',
    syntax: 'normal | <string>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-optical-sizing': {
    alias: 'fos',
    type: 'typography',
    syntax: 'auto | none',
    compiler: (v) => v,
    values: ['auto:a', 'none:n'],
  },
  'font-palette': {
    alias: 'fp',
    type: 'typography',
    syntax: 'normal | light | dark | <palette-identifier>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-size': {
    alias: 'fs',
    type: 'typography',
    syntax: '[<absolute-size> | <relative-size> | <length-percentage>] && [/ <line-height>]?',
    compiler: (v) => v,
    values: ['xx-small:xxs', 'x-small:xs', 'small:s', 'medium:m', 'large:l', 'x-large:xl', 'xx-large:xxl'],
  },
  'font-size-adjust': {
    alias: 'fsa',
    type: 'typography',
    syntax: 'none | from-font | [<number> && [ex-height | cap-height | ch-width | ic-width | ic-height]?]',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'font-smooth': {
    alias: 'fsm',
    type: 'typography',
    syntax: 'auto | never | always',
    compiler: (v) => v,
    values: ['auto:a', 'never:n', 'always:a'],
  },
  'font-stretch': {
    alias: 'fst',
    type: 'typography',
    syntax:
      '<percentage> | ultra-condensed | extra-condensed | condensed | semi-condensed | normal | semi-expanded | expanded | extra-expanded | ultra-expanded',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-style': {
    alias: 'fs',
    type: 'typography',
    syntax: 'normal | italic | oblique <angle>?',
    compiler: (v) => v,
    values: ['normal:n', 'italic:i', 'oblique:o'],
  },
  'font-synthesis': {
    alias: 'fsyn',
    type: 'typography',
    syntax: 'none | [weight || style || small-caps]',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'font-synthesis-position': {
    alias: 'fsp',
    type: 'typography',
    syntax: 'none | normal',
    compiler: (v) => v,
    values: ['none:n', 'normal:n'],
  },
  'font-synthesis-small-caps': {
    alias: 'fssc',
    type: 'typography',
    syntax: 'none | normal',
    compiler: (v) => v,
    values: ['none:n', 'normal:n'],
  },
  'font-synthesis-style': {
    alias: 'fsst',
    type: 'typography',
    syntax: 'none | normal',
    compiler: (v) => v,
    values: ['none:n', 'normal:n'],
  },
  'font-synthesis-weight': {
    alias: 'fssw',
    type: 'typography',
    syntax: 'none | normal',
    compiler: (v) => v,
    values: ['none:n', 'normal:n'],
  },
  'font-variant': {
    alias: 'fv',
    type: 'typography',
    syntax:
      'normal | none | [<common-lig-values> || <contextual-alt-values> || [small-caps | all-small-caps | petite-caps | all-petite-caps | unicase | titling-caps] || <numeric-figure-values> || <numeric-spacing-values> || <numeric-position-values> || <east-asian-variant-values> || <east-asian-width-values> || ruby]',
    compiler: (v) => v,
    values: ['normal:n', 'none:n'],
  },
  'font-variant-alternates': {
    alias: 'fva',
    type: 'typography',
    syntax:
      'normal | [stylistic(<feature-value-name>) || historical-forms || styleset(<feature-value-name>#) || character-variant(<feature-value-name>#) || swash(<feature-value-name>) || ornaments(<feature-value-name>) || annotation(<feature-value-name>)]',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-variant-caps': {
    alias: 'fvc',
    type: 'typography',
    syntax: 'normal | small-caps | all-small-caps | petite-caps | all-petite-caps | unicase | titling-caps',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-variant-east-asian': {
    alias: 'fvea',
    type: 'typography',
    syntax:
      'normal | [[jis78 | jis83 | jis90 | jis04 | simplified | traditional] || [full-width | proportional-width] || ruby]',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-variant-emoji': {
    alias: 'fve',
    type: 'typography',
    syntax: 'normal | text | emoji | unicode',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-variant-ligatures': {
    alias: 'fvl',
    type: 'typography',
    syntax:
      'normal | none | [<common-lig-values> || <contextual-alt-values> || [historical-lig-values] || [discretionary-lig-values]]',
    compiler: (v) => v,
    values: ['normal:n', 'none:n'],
  },
  'font-variant-numeric': {
    alias: 'fvn',
    type: 'typography',
    syntax: 'normal | [[<numeric-figure-values> || <numeric-spacing-values> || <numeric-position-values>]]',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-variant-position': {
    alias: 'fvp',
    type: 'typography',
    syntax: 'normal | sub | super',
    compiler: (v) => v,
    values: ['normal:n', 'sub:s', 'super:sp'],
  },
  'font-variation-settings': {
    alias: 'fvs',
    type: 'typography',
    syntax: 'normal | <string> <number>#',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'font-weight': {
    alias: 'fw',
    type: 'typography',
    syntax: '<font-weight-absolute> | bolder | lighter',
    compiler: (v) => v,
    values: [
      'normal:n',
      'bold:b',
      'lighter:l',
      'bolder:br',
      '100:1',
      '200:2',
      '300:3',
      '400:4',
      '500:5',
      '600:6',
      '700:7',
      '800:8',
      '900:9',
    ],
  },
  gap: { alias: 'gap', type: 'layout', syntax: "<'row-gap'> <'column-gap'>?", compiler: (v) => v, values: [] },
  'glyph-orientation-horizontal': {
    alias: 'goh',
    type: 'typography',
    syntax: '0deg | 90deg | 180deg | 270deg',
    compiler: (v) => v,
    values: [],
  },
  'glyph-orientation-vertical': {
    alias: 'gov',
    type: 'typography',
    syntax: 'auto | 0deg | 90deg | 180deg | 270deg',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  grid: {
    alias: 'g',
    type: 'grid',
    syntax:
      "<'grid-template'> | <'grid-template-rows'> / [auto-flow && dense?] <'grid-auto-columns'>? | [auto-flow && dense?] <'grid-auto-rows'>? / <'grid-template-columns'>",
    compiler: (v) => v,
    values: [],
  },
  'grid-area': {
    alias: 'ga',
    type: 'grid',
    syntax: '<grid-line> [/ <grid-line>]{0,2}',
    compiler: (v) => v,
    values: [],
  },
  'grid-auto-columns': { alias: 'gac', type: 'grid', syntax: '<track-size>+', compiler: (v) => v, values: ['auto:a'] },
  'grid-auto-flow': {
    alias: 'gaf',
    type: 'grid',
    syntax: '[row | column] || dense',
    compiler: (v) => v,
    values: ['row:r', 'column:c', 'dense:d'],
  },
  'grid-auto-rows': { alias: 'gar', type: 'grid', syntax: '<track-size>+', compiler: (v) => v, values: ['auto:a'] },
  'grid-column': { alias: 'gc', type: 'grid', syntax: '<grid-line> [/ <grid-line>]?', compiler: (v) => v, values: [] },
  'grid-column-end': { alias: 'gce', type: 'grid', syntax: '<grid-line>', compiler: (v) => v, values: [] },
  'grid-column-gap': { alias: 'gcg', type: 'grid', syntax: '<length-percentage>', compiler: (v) => v, values: [] },
  'grid-column-start': { alias: 'gcs', type: 'grid', syntax: '<grid-line>', compiler: (v) => v, values: [] },
  'grid-gap': {
    alias: 'gg',
    type: 'grid',
    syntax: "<'grid-row-gap'> <'grid-column-gap'>?",
    compiler: (v) => v,
    values: [],
  },
  'grid-row': { alias: 'gr', type: 'grid', syntax: '<grid-line> [/ <grid-line>]?', compiler: (v) => v, values: [] },
  'grid-row-end': { alias: 'gre', type: 'grid', syntax: '<grid-line>', compiler: (v) => v, values: [] },
  'grid-row-gap': { alias: 'grg', type: 'grid', syntax: '<length-percentage>', compiler: (v) => v, values: [] },
  'grid-row-start': { alias: 'grs', type: 'grid', syntax: '<grid-line>', compiler: (v) => v, values: [] },
  'grid-template': {
    alias: 'gt',
    type: 'grid',
    syntax: "none | [<'grid-template-rows'> / <'grid-template-columns'>]",
    compiler: (v) => v,
    values: ['none:n'],
  },
  'grid-template-areas': {
    alias: 'gta',
    type: 'grid',
    syntax: 'none | <string>+',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'grid-template-columns': {
    alias: 'gtc',
    type: 'grid',
    syntax: 'none | <track-list> | <auto-track-list>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'grid-template-rows': {
    alias: 'gtr',
    type: 'grid',
    syntax: 'none | <track-list> | <auto-track-list>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  height: {
    alias: 'h',
    type: 'size',
    syntax: 'auto | <length> | <percentage> | min-content | max-content | fit-content(<length-percentage>)',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'hyphenate-character': {
    alias: 'hc',
    type: 'typography',
    syntax: 'auto | <string>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'hyphenate-limit-chars': {
    alias: 'hlc',
    type: 'typography',
    syntax: 'auto | [<integer> | auto]{1,2}',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'hyphenate-limit-last': {
    alias: 'hll',
    type: 'typography',
    syntax: 'none | always | column | page | spread',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'hyphenate-limit-zone': {
    alias: 'hlz',
    type: 'typography',
    syntax: '<percentage> | <length>',
    compiler: (v) => v,
    values: [],
  },
  hyphens: {
    alias: 'hyp',
    type: 'typography',
    syntax: 'none | manual | auto',
    compiler: (v) => v,
    values: ['none:n', 'manual:m', 'auto:a'],
  },
  'image-orientation': {
    alias: 'io',
    type: 'image',
    syntax: 'from-image | none | [<angle> | <turn>] && flip?',
    compiler: (v) => v,
    values: ['from-image', 'none:n'],
  },
  'image-rendering': {
    alias: 'ir',
    type: 'image',
    syntax: 'auto | crisp-edges | pixelated | -webkit-optimize-contrast',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'image-resolution': {
    alias: 'ires',
    type: 'image',
    syntax: '[from-image || <resolution>] && snap?',
    compiler: (v) => v,
    values: ['from-image'],
  },
  'ime-mode': {
    alias: 'im',
    type: 'ui',
    syntax: 'auto | normal | active | inactive | disabled',
    compiler: (v) => v,
    values: ['auto:a', 'normal:n'],
  },
  'initial-letter': {
    alias: 'il',
    type: 'typography',
    syntax: 'normal | [<number> <integer>?]',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'initial-letter-align': {
    alias: 'ila',
    type: 'typography',
    syntax: '[ auto | alphabetic | hanging | ideographic ]',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'inline-size': {
    alias: 'is',
    type: 'size',
    syntax: 'auto | <length-percentage> | min-content | max-content | fit-content(<length-percentage>)',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  inset: { alias: 'i', type: 'position', syntax: "<'top'>{1,4}", compiler: (v) => v, values: [] },
  'inset-block': { alias: 'ib', type: 'position', syntax: "<'top'>{1,2}", compiler: (v) => v, values: [] },
  'inset-block-end': { alias: 'ibe', type: 'position', syntax: "<'top'>", compiler: (v) => v, values: [] },
  'inset-block-start': { alias: 'ibs', type: 'position', syntax: "<'top'>", compiler: (v) => v, values: [] },
  'inset-inline': { alias: 'ii', type: 'position', syntax: "<'top'>{1,2}", compiler: (v) => v, values: [] },
  'inset-inline-end': { alias: 'iie', type: 'position', syntax: "<'top'>", compiler: (v) => v, values: [] },
  'inset-inline-start': { alias: 'iis', type: 'position', syntax: "<'top'>", compiler: (v) => v, values: [] },
  'input-security': {
    alias: 'is',
    type: 'ui',
    syntax: 'none | auto',
    compiler: (v) => v,
    values: ['none:n', 'auto:a'],
  },
  isolation: {
    alias: 'iso',
    type: 'visual',
    syntax: 'auto | isolate',
    compiler: (v) => v,
    values: ['auto:a', 'isolate:i'],
  },
  'justify-content': {
    alias: 'jc',
    type: 'layout',
    syntax: 'normal | <content-distribution> | <overflow-position>? [<content-position> | left | right]',
    compiler: (v) => v,
    values: [
      'normal:n',
      'center:c',
      'flex-start:fs',
      'flex-end:fe',
      'space-between:sb',
      'space-around:sa',
      'space-evenly:se',
    ],
  },
  'justify-items': {
    alias: 'ji',
    type: 'layout',
    syntax:
      'normal | stretch | <baseline-position> | <overflow-position>? [<self-position> | left | right] | legacy | legacy && [left | right | center]',
    compiler: (v) => v,
    values: ['normal:n', 'center:c', 'stretch:s'],
  },
  'justify-self': {
    alias: 'js',
    type: 'layout',
    syntax: 'auto | normal | stretch | <baseline-position> | <overflow-position>? [<self-position> | left | right]',
    compiler: (v) => v,
    values: ['auto:a', 'normal:n', 'center:c', 'stretch:s'],
  },
  'justify-tracks': {
    alias: 'jt',
    type: 'layout',
    syntax: 'normal | <content-distribution> | <overflow-position>? [<content-position> | left | right]',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  kerning: {
    alias: 'k',
    type: 'typography',
    syntax: 'auto | <length> | <percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  left: { alias: 'l', type: 'position', syntax: 'auto | <length-percentage>', compiler: (v) => v, values: ['auto:a'] },
  'letter-spacing': {
    alias: 'ls',
    type: 'typography',
    syntax: 'normal | <length-percentage>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'lighting-color': { alias: 'lc', type: 'color', syntax: '<color>', compiler: (v) => v, values: [] },
  'line-break': {
    alias: 'lb',
    type: 'typography',
    syntax: 'auto | loose | normal | strict | anywhere',
    compiler: (v) => v,
    values: ['auto:a', 'loose:l', 'normal:n', 'strict:s'],
  },
  'line-clamp': { alias: 'lc', type: 'typography', syntax: 'none | <integer>', compiler: (v) => v, values: ['none:n'] },
  'line-height': {
    alias: 'lh',
    type: 'typography',
    syntax: 'normal | <number> | <length> | <percentage>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'line-height-step': { alias: 'lhs', type: 'typography', syntax: '<length>', compiler: (v) => v, values: [] },
  'list-style': {
    alias: 'ls',
    type: 'layout',
    syntax: "<'list-style-position'> || <'list-style-image'> || <'list-style-type'>",
    compiler: (v) => v,
    values: [],
  },
  'list-style-image': {
    alias: 'lsi',
    type: 'layout',
    syntax: '<image> | none',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'list-style-position': {
    alias: 'lsp',
    type: 'layout',
    syntax: 'inside | outside',
    compiler: (v) => v,
    values: ['inside:i', 'outside:o'],
  },
  'list-style-type': {
    alias: 'lst',
    type: 'layout',
    syntax: '<counter-style> | <string> | none',
    compiler: (v) => v,
    values: ['none:n'],
  },
  margin: { alias: 'm', type: 'spacing', syntax: "<'margin-left'>{1,4}", compiler: (v) => v, values: [] },
  'margin-block': { alias: 'mb', type: 'spacing', syntax: "<'margin-left'>{1,2}", compiler: (v) => v, values: [] },
  'margin-block-end': { alias: 'mbe', type: 'spacing', syntax: "<'margin-left'>", compiler: (v) => v, values: [] },
  'margin-block-start': { alias: 'mbs', type: 'spacing', syntax: "<'margin-left'>", compiler: (v) => v, values: [] },
  'margin-bottom': {
    alias: 'mb',
    type: 'spacing',
    syntax: '<length-percentage> | auto',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'margin-inline': { alias: 'mi', type: 'spacing', syntax: "<'margin-left'>{1,2}", compiler: (v) => v, values: [] },
  'margin-inline-end': { alias: 'mie', type: 'spacing', syntax: "<'margin-left'>", compiler: (v) => v, values: [] },
  'margin-inline-start': { alias: 'mis', type: 'spacing', syntax: "<'margin-left'>", compiler: (v) => v, values: [] },
  'margin-left': {
    alias: 'ml',
    type: 'spacing',
    syntax: '<length-percentage> | auto',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'margin-right': {
    alias: 'mr',
    type: 'spacing',
    syntax: '<length-percentage> | auto',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'margin-top': {
    alias: 'mt',
    type: 'spacing',
    syntax: '<length-percentage> | auto',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'margin-trim': {
    alias: 'mtrim',
    type: 'spacing',
    syntax: 'none | in-flow | all',
    compiler: (v) => v,
    values: ['none:n'],
  },
  marker: { alias: 'm', type: 'svg', syntax: 'none | <url>', compiler: (v) => v, values: ['none:n'] },
  'marker-end': { alias: 'me', type: 'svg', syntax: 'none | <url>', compiler: (v) => v, values: ['none:n'] },
  'marker-mid': { alias: 'mm', type: 'svg', syntax: 'none | <url>', compiler: (v) => v, values: ['none:n'] },
  'marker-start': { alias: 'ms', type: 'svg', syntax: 'none | <url>', compiler: (v) => v, values: ['none:n'] },
  mask: { alias: 'mask', type: 'layout', syntax: '<mask-layer>#', compiler: (v) => v, values: [] },
  'mask-border': {
    alias: 'mb',
    type: 'layout',
    syntax:
      "<'mask-border-source'> || <'mask-border-slice'> [/ <'mask-border-width'>]? [/ <'mask-border-outset'>]? || <'mask-border-repeat'> || <'mask-border-mode'>",
    compiler: (v) => v,
    values: [],
  },
  'mask-border-mode': {
    alias: 'mbm',
    type: 'layout',
    syntax: 'luminance | alpha',
    compiler: (v) => v,
    values: ['luminance:l', 'alpha:a'],
  },
  'mask-border-outset': {
    alias: 'mbo',
    type: 'layout',
    syntax: '[<length> | <number>]{1,4}',
    compiler: (v) => v,
    values: [],
  },
  'mask-border-repeat': {
    alias: 'mbr',
    type: 'layout',
    syntax: '[stretch | repeat | round | space]{1,2}',
    compiler: (v) => v,
    values: ['stretch:s', 'repeat:r', 'round:ro', 'space:sp'],
  },
  'mask-border-slice': {
    alias: 'mbs',
    type: 'layout',
    syntax: '<number-percentage>{1,4} fill?',
    compiler: (v) => v,
    values: [],
  },
  'mask-border-source': {
    alias: 'mbsrc',
    type: 'layout',
    syntax: 'none | <image>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'mask-border-width': {
    alias: 'mbw',
    type: 'layout',
    syntax: '[<length-percentage> | <number> | auto]{1,4}',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'mask-clip': {
    alias: 'mc',
    type: 'layout',
    syntax: '[border-box | padding-box | content-box | fill-box | stroke-box | view-box]#',
    compiler: (v) => v,
    values: [],
  },
  'mask-composite': {
    alias: 'mcomp',
    type: 'layout',
    syntax: '[add | subtract | intersect | exclude]#',
    compiler: (v) => v,
    values: ['add:a', 'subtract:s', 'intersect:i', 'exclude:e'],
  },
  'mask-image': {
    alias: 'mi',
    type: 'layout',
    syntax: '[none | <image> | <mask-reference>]#',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'mask-mode': {
    alias: 'mm',
    type: 'layout',
    syntax: '[alpha | luminance | match-source]#',
    compiler: (v) => v,
    values: ['alpha:a', 'luminance:l'],
  },
  'mask-origin': {
    alias: 'mo',
    type: 'layout',
    syntax: '[border-box | padding-box | content-box | fill-box | stroke-box | view-box]#',
    compiler: (v) => v,
    values: [],
  },
  'mask-position': { alias: 'mp', type: 'layout', syntax: '<position>#', compiler: (v) => v, values: [] },
  'mask-repeat': { alias: 'mr', type: 'layout', syntax: '<repeat-style>#', compiler: (v) => v, values: [] },
  'mask-size': {
    alias: 'ms',
    type: 'layout',
    syntax: '[<length-percentage> | auto]{1,2} | cover | contain',
    compiler: (v) => v,
    values: ['auto:a', 'cover:c', 'contain:cn'],
  },
  'mask-type': {
    alias: 'mt',
    type: 'layout',
    syntax: 'luminance | alpha',
    compiler: (v) => v,
    values: ['luminance:l', 'alpha:a'],
  },
  'math-depth': {
    alias: 'md',
    type: 'layout',
    syntax: 'auto-add | add(<integer>) | <integer>',
    compiler: (v) => v,
    values: ['auto-add'],
  },
  'math-shift': {
    alias: 'ms',
    type: 'layout',
    syntax: 'normal | compact',
    compiler: (v) => v,
    values: ['normal:n', 'compact:c'],
  },
  'math-style': {
    alias: 'mst',
    type: 'layout',
    syntax: 'normal | compact',
    compiler: (v) => v,
    values: ['normal:n', 'compact:c'],
  },
  'max-block-size': {
    alias: 'mbs',
    type: 'size',
    syntax: 'none | <length-percentage> | min-content | max-content | fit-content(<length-percentage>)',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'max-height': {
    alias: 'mh',
    type: 'size',
    syntax: 'none | <length-percentage> | min-content | max-content | fit-content(<length-percentage>)',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'max-inline-size': {
    alias: 'mis',
    type: 'size',
    syntax: 'none | <length-percentage> | min-content | max-content | fit-content(<length-percentage>)',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'max-lines': { alias: 'ml', type: 'layout', syntax: 'none | <integer>', compiler: (v) => v, values: ['none:n'] },
  'max-width': {
    alias: 'mw',
    type: 'size',
    syntax: 'none | <length-percentage> | min-content | max-content | fit-content(<length-percentage>) | <calc-size()>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'min-block-size': {
    alias: 'mibs',
    type: 'size',
    syntax: 'auto | <length-percentage> | min-content | max-content | fit-content(<length-percentage>)',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'min-height': {
    alias: 'mih',
    type: 'size',
    syntax: 'auto | <length-percentage> | min-content | max-content | fit-content(<length-percentage>)',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'min-inline-size': {
    alias: 'miis',
    type: 'size',
    syntax: 'auto | <length-percentage> | min-content | max-content | fit-content(<length-percentage>)',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'min-width': {
    alias: 'miw',
    type: 'size',
    syntax: 'auto | <length-percentage> | min-content | max-content | fit-content(<length-percentage>) | <calc-size()>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'mix-blend-mode': { alias: 'mbm', type: 'visual', syntax: '<blend-mode>', compiler: (v) => v, values: [] },
  'object-fit': {
    alias: 'of',
    type: 'layout',
    syntax: 'fill | contain | cover | scale-down | none',
    compiler: (v) => v,
    values: ['fill:f', 'contain:c', 'cover:co', 'scale-down:sd', 'none:n'],
  },
  'object-position': { alias: 'op', type: 'layout', syntax: '<position>', compiler: (v) => v, values: [] },
  'object-view-box': {
    alias: 'ovb',
    type: 'layout',
    syntax: 'none | <rect()>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  offset: {
    alias: 'o',
    type: 'motion',
    syntax:
      "[<'offset-position'>? [<'offset-path'> [<'offset-distance'> || <'offset-rotate'>]?]!] || <'offset-anchor'>",
    compiler: (v) => v,
    values: [],
  },
  'offset-anchor': { alias: 'oa', type: 'motion', syntax: 'auto | <position>', compiler: (v) => v, values: ['auto:a'] },
  'offset-distance': { alias: 'od', type: 'motion', syntax: '<length-percentage>', compiler: (v) => v, values: [] },
  'offset-path': {
    alias: 'op',
    type: 'motion',
    syntax:
      'none | ray([ [<angle> && <size>? && contain?] | [at <position>] ]) | <path()> | <url> | [ <basic-shape> || <geometry-box> ]',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'offset-position': {
    alias: 'opos',
    type: 'motion',
    syntax: 'auto | <position>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'offset-rotate': {
    alias: 'or',
    type: 'motion',
    syntax: '[auto | reverse] || <angle>',
    compiler: (v) => v,
    values: ['auto:a', 'reverse:r'],
  },
  opacity: { alias: 'op', type: 'visual', syntax: '<number-percentage>', compiler: (v) => parseFloat(v), values: [] },
  order: { alias: 'o', type: 'layout', syntax: '<integer>', compiler: (v) => parseInt(v), values: [] },
  orphans: { alias: 'orph', type: 'layout', syntax: '<integer>', compiler: (v) => parseInt(v), values: [] },
  outline: {
    alias: 'out',
    type: 'border',
    syntax: "[<'outline-color'> || <'outline-style'> || <'outline-width'>]",
    compiler: (v) => v,
    values: [],
  },
  'outline-color': {
    alias: 'outc',
    type: 'border',
    syntax: '<color> | invert',
    compiler: (v) => v,
    values: ['invert:i'],
  },
  'outline-offset': { alias: 'outo', type: 'border', syntax: '<length>', compiler: (v) => v, values: [] },
  'outline-style': {
    alias: 'outs',
    type: 'border',
    syntax: "auto | <'border-style'>",
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'outline-width': { alias: 'outw', type: 'border', syntax: "<'border-width'>", compiler: (v) => v, values: [] },
  overflow: {
    alias: 'ov',
    type: 'layout',
    syntax: '[visible | hidden | clip | scroll | auto]{1,2}',
    compiler: (v) => v,
    values: ['visible:v', 'hidden:h', 'scroll:s', 'auto:a'],
  },
  'overflow-anchor': {
    alias: 'ova',
    type: 'layout',
    syntax: 'auto | none',
    compiler: (v) => v,
    values: ['auto:a', 'none:n'],
  },
  'overflow-block': {
    alias: 'ovb',
    type: 'layout',
    syntax: 'visible | hidden | clip | scroll | auto',
    compiler: (v) => v,
    values: ['visible:v', 'hidden:h'],
  },
  'overflow-inline': {
    alias: 'ovi',
    type: 'layout',
    syntax: 'visible | hidden | clip | scroll | auto',
    compiler: (v) => v,
    values: ['visible:v', 'hidden:h'],
  },
  'overflow-wrap': {
    alias: 'ovw',
    type: 'typography',
    syntax: 'normal | break-word | anywhere',
    compiler: (v) => v,
    values: ['normal:n', 'break-word:bw', 'anywhere:a'],
  },
  'overflow-x': {
    alias: 'ovx',
    type: 'layout',
    syntax: 'visible | hidden | clip | scroll | auto',
    compiler: (v) => v,
    values: ['visible:v', 'hidden:h', 'scroll:s', 'auto:a'],
  },
  'overflow-y': {
    alias: 'ovy',
    type: 'layout',
    syntax: 'visible | hidden | clip | scroll | auto',
    compiler: (v) => v,
    values: ['visible:v', 'hidden:h', 'scroll:s', 'auto:a'],
  },
  'overscroll-behavior': {
    alias: 'ob',
    type: 'layout',
    syntax: '[contain | none | auto]{1,2}',
    compiler: (v) => v,
    values: ['contain:c', 'none:n', 'auto:a'],
  },
  'overscroll-behavior-block': {
    alias: 'obb',
    type: 'layout',
    syntax: 'contain | none | auto',
    compiler: (v) => v,
    values: ['contain:c', 'none:n', 'auto:a'],
  },
  'overscroll-behavior-inline': {
    alias: 'obi',
    type: 'layout',
    syntax: 'contain | none | auto',
    compiler: (v) => v,
    values: ['contain:c', 'none:n', 'auto:a'],
  },
  'overscroll-behavior-x': {
    alias: 'obx',
    type: 'layout',
    syntax: 'contain | none | auto',
    compiler: (v) => v,
    values: ['contain:c', 'none:n', 'auto:a'],
  },
  'overscroll-behavior-y': {
    alias: 'oby',
    type: 'layout',
    syntax: 'contain | none | auto',
    compiler: (v) => v,
    values: ['contain:c', 'none:n', 'auto:a'],
  },
  'paint-order': {
    alias: 'po',
    type: 'svg',
    syntax: 'normal | [fill || stroke || markers]',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  padding: { alias: 'p', type: 'spacing', syntax: "<'padding-left'>{1,4}", compiler: (v) => v, values: [] },
  'padding-block': { alias: 'pb', type: 'spacing', syntax: "<'padding-left'>{1,2}", compiler: (v) => v, values: [] },
  'padding-block-end': { alias: 'pbe', type: 'spacing', syntax: "<'padding-left'>", compiler: (v) => v, values: [] },
  'padding-block-start': { alias: 'pbs', type: 'spacing', syntax: "<'padding-left'>", compiler: (v) => v, values: [] },
  'padding-bottom': { alias: 'pb', type: 'spacing', syntax: '<length-percentage>', compiler: (v) => v, values: [] },
  'padding-inline': { alias: 'pi', type: 'spacing', syntax: "<'padding-left'>{1,2}", compiler: (v) => v, values: [] },
  'padding-inline-end': { alias: 'pie', type: 'spacing', syntax: "<'padding-left'>", compiler: (v) => v, values: [] },
  'padding-inline-start': { alias: 'pis', type: 'spacing', syntax: "<'padding-left'>", compiler: (v) => v, values: [] },
  'padding-left': { alias: 'pl', type: 'spacing', syntax: '<length-percentage>', compiler: (v) => v, values: [] },
  'padding-right': { alias: 'pr', type: 'spacing', syntax: '<length-percentage>', compiler: (v) => v, values: [] },
  'padding-top': { alias: 'pt', type: 'spacing', syntax: '<length-percentage>', compiler: (v) => v, values: [] },
  page: { alias: 'page', type: 'layout', syntax: 'auto | <custom-ident>', compiler: (v) => v, values: ['auto:a'] },
  'page-break-after': {
    alias: 'pba',
    type: 'layout',
    syntax: 'auto | always | avoid | left | right | inherit',
    compiler: (v) => v,
    values: ['auto:a', 'always:al', 'avoid:av'],
  },
  'page-break-before': {
    alias: 'pbb',
    type: 'layout',
    syntax: 'auto | always | avoid | left | right | inherit',
    compiler: (v) => v,
    values: ['auto:a', 'always:al', 'avoid:av'],
  },
  'page-break-inside': {
    alias: 'pbi',
    type: 'layout',
    syntax: 'avoid | auto | inherit',
    compiler: (v) => v,
    values: ['auto:a', 'avoid:av'],
  },
  'page-orientation': {
    alias: 'po',
    type: 'layout',
    syntax: 'portrait | landscape',
    compiler: (v) => v,
    values: ['portrait:p', 'landscape:l'],
  },
  paint: { alias: 'p', type: 'paint', syntax: 'none | <color> | <url>', compiler: (v) => v, values: ['none:n'] },
  perspective: { alias: 'pers', type: '3d', syntax: 'none | <length>', compiler: (v) => v, values: ['none:n'] },
  'perspective-origin': { alias: 'perso', type: '3d', syntax: '<position>', compiler: (v) => v, values: [] },
  'place-content': {
    alias: 'pc',
    type: 'layout',
    syntax: "<'align-content'> <'justify-content'>?",
    compiler: (v) => v,
    values: [],
  },
  'place-items': {
    alias: 'pi',
    type: 'layout',
    syntax: "<'align-items'> <'justify-items'>?",
    compiler: (v) => v,
    values: [],
  },
  'place-self': {
    alias: 'ps',
    type: 'layout',
    syntax: "<'align-self'> <'justify-self'>?",
    compiler: (v) => v,
    values: [],
  },
  'pointer-events': {
    alias: 'pe',
    type: 'ui',
    syntax:
      'auto | none | visiblePainted | visibleFill | visibleStroke | visible | painted | fill | stroke | all | inherit',
    compiler: (v) => v,
    values: ['auto:a', 'none:n'],
  },
  position: {
    alias: 'pos',
    type: 'layout',
    syntax: 'static | relative | absolute | sticky | fixed',
    compiler: (v) => v,
    values: ['static:s', 'relative:r', 'absolute:a', 'sticky:st', 'fixed:f'],
  },
  'print-color-adjust': {
    alias: 'pca',
    type: 'color',
    syntax: 'economy | exact',
    compiler: (v) => v,
    values: ['economy:e', 'exact:e'],
  },
  quotes: {
    alias: 'q',
    type: 'typography',
    syntax: 'none | auto | [<string> <string>]+',
    compiler: (v) => v,
    values: ['none:n', 'auto:a'],
  },
  r: { alias: 'r', type: 'svg', syntax: '<length-percentage>', compiler: (v) => v, values: [] },
  range: { alias: 'range', type: 'font', syntax: '<urange>#', compiler: (v) => v, values: [] },
  'relative-size-adjustment': {
    alias: 'rsa',
    type: 'typography',
    syntax: 'normal | from-font',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  resize: {
    alias: 'rsz',
    type: 'ui',
    syntax: 'none | both | horizontal | vertical | block | inline',
    compiler: (v) => v,
    values: ['none:n', 'both:b', 'horizontal:h', 'vertical:v'],
  },
  right: { alias: 'r', type: 'position', syntax: 'auto | <length-percentage>', compiler: (v) => v, values: ['auto:a'] },
  rotate: {
    alias: 'ro',
    type: 'motion',
    syntax: 'none | <angle> | [x | y | z | <number>{3}] && <angle>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'row-gap': {
    alias: 'rg',
    type: 'spacing',
    syntax: 'normal | <length-percentage>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'ruby-align': {
    alias: 'ra',
    type: 'typography',
    syntax: 'start | center | space-between | space-around',
    compiler: (v) => v,
    values: ['start:s', 'center:c'],
  },
  'ruby-position': {
    alias: 'rp',
    type: 'typography',
    syntax: 'over | under | inter-character',
    compiler: (v) => v,
    values: ['over:o', 'under:u'],
  },
  rx: { alias: 'rx', type: 'svg', syntax: '<length-percentage> | auto', compiler: (v) => v, values: ['auto:a'] },
  ry: { alias: 'ry', type: 'svg', syntax: '<length-percentage> | auto', compiler: (v) => v, values: ['auto:a'] },
  scale: { alias: 'scl', type: 'motion', syntax: 'none | <number>{1,3}', compiler: (v) => v, values: ['none:n'] },
  'scroll-behavior': {
    alias: 'sb',
    type: 'layout',
    syntax: 'auto | smooth',
    compiler: (v) => v,
    values: ['auto:a', 'smooth:s'],
  },
  'scroll-margin': { alias: 'sm', type: 'layout', syntax: '<length>{1,4}', compiler: (v) => v, values: [] },
  'scroll-margin-block': { alias: 'smb', type: 'layout', syntax: '<length>{1,2}', compiler: (v) => v, values: [] },
  'scroll-margin-block-end': { alias: 'smbe', type: 'layout', syntax: '<length>', compiler: (v) => v, values: [] },
  'scroll-margin-block-start': { alias: 'smbs', type: 'layout', syntax: '<length>', compiler: (v) => v, values: [] },
  'scroll-margin-bottom': { alias: 'smb', type: 'layout', syntax: '<length>', compiler: (v) => v, values: [] },
  'scroll-margin-inline': { alias: 'smi', type: 'layout', syntax: '<length>{1,2}', compiler: (v) => v, values: [] },
  'scroll-margin-inline-end': { alias: 'smie', type: 'layout', syntax: '<length>', compiler: (v) => v, values: [] },
  'scroll-margin-inline-start': { alias: 'smis', type: 'layout', syntax: '<length>', compiler: (v) => v, values: [] },
  'scroll-margin-left': { alias: 'sml', type: 'layout', syntax: '<length>', compiler: (v) => v, values: [] },
  'scroll-margin-right': { alias: 'smr', type: 'layout', syntax: '<length>', compiler: (v) => v, values: [] },
  'scroll-margin-top': { alias: 'smt', type: 'layout', syntax: '<length>', compiler: (v) => v, values: [] },
  'scroll-padding': {
    alias: 'sp',
    type: 'layout',
    syntax: '[auto | <length-percentage>]{1,4}',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-block': {
    alias: 'spb',
    type: 'layout',
    syntax: '[auto | <length-percentage>]{1,2}',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-block-end': {
    alias: 'spbe',
    type: 'layout',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-block-start': {
    alias: 'spbs',
    type: 'layout',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-bottom': {
    alias: 'spb',
    type: 'layout',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-inline': {
    alias: 'spi',
    type: 'layout',
    syntax: '[auto | <length-percentage>]{1,2}',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-inline-end': {
    alias: 'spie',
    type: 'layout',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-inline-start': {
    alias: 'spis',
    type: 'layout',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-left': {
    alias: 'spl',
    type: 'layout',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-right': {
    alias: 'spr',
    type: 'layout',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-padding-top': {
    alias: 'spt',
    type: 'layout',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'scroll-snap-align': {
    alias: 'ssa',
    type: 'layout',
    syntax: 'none | [start | end | center]{1,2}',
    compiler: (v) => v,
    values: ['none:n', 'start:s', 'end:e', 'center:c'],
  },
  'scroll-snap-coordinate': {
    alias: 'ssc',
    type: 'layout',
    syntax: 'none | <position>#',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'scroll-snap-destination': { alias: 'ssd', type: 'layout', syntax: '<position>', compiler: (v) => v, values: [] },
  'scroll-snap-points-x': {
    alias: 'sspx',
    type: 'layout',
    syntax: 'none | repeat(<length-percentage>)',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'scroll-snap-points-y': {
    alias: 'sspy',
    type: 'layout',
    syntax: 'none | repeat(<length-percentage>)',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'scroll-snap-stop': {
    alias: 'ssst',
    type: 'layout',
    syntax: 'normal | always',
    compiler: (v) => v,
    values: ['normal:n', 'always:a'],
  },
  'scroll-snap-type': {
    alias: 'sst',
    type: 'layout',
    syntax: 'none | [x | y | block | inline | both] [mandatory | proximity]?',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'scroll-timeline': {
    alias: 'stl',
    type: 'motion',
    syntax: '[<timeline-name> <axis>? <position>?]#',
    compiler: (v) => v,
    values: [],
  },
  'scroll-timeline-axis': {
    alias: 'stla',
    type: 'motion',
    syntax: 'block | inline | x | y | vertical | horizontal',
    compiler: (v) => v,
    values: [],
  },
  'scroll-timeline-name': {
    alias: 'stln',
    type: 'motion',
    syntax: 'none | <custom-ident>#',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'scrollbar-color': { alias: 'sc', type: 'ui', syntax: 'auto | <color>{2}', compiler: (v) => v, values: ['auto:a'] },
  'scrollbar-gutter': {
    alias: 'sg',
    type: 'ui',
    syntax: 'auto | stable',
    compiler: (v) => v,
    values: ['auto:a', 'stable:s'],
  },
  'scrollbar-width': {
    alias: 'sw',
    type: 'ui',
    syntax: 'auto | thin | none',
    compiler: (v) => v,
    values: ['auto:a', 'thin:t', 'none:n'],
  },
  'shape-image-threshold': {
    alias: 'sit',
    type: 'layout',
    syntax: '<number> | <percentage>',
    compiler: (v) => v,
    values: [],
  },
  'shape-margin': { alias: 'sm', type: 'layout', syntax: '<length-percentage>', compiler: (v) => v, values: [] },
  'shape-outside': {
    alias: 'so',
    type: 'layout',
    syntax: 'none | [<basic-shape> || <shape-box>] | <image>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'shape-rendering': {
    alias: 'sr',
    type: 'svg',
    syntax: 'auto | optimizeSpeed | crispEdges | geometricPrecision',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  shell: {
    alias: 'shell',
    type: 'ui',
    syntax: 'none | standard',
    compiler: (v) => v,
    values: ['none:n', 'standard:s'],
  },
  'shift-position': { alias: 'sp', type: 'motion', syntax: '<percentage>', compiler: (v) => v, values: [] },
  'shift-row': { alias: 'sr', type: 'motion', syntax: 'none | <percentage>', compiler: (v) => v, values: ['none:n'] },
  size: {
    alias: 'siz',
    type: 'layout',
    syntax: '<length>{1,2} | auto | [<page-size> || [portrait | landscape]]',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  speak: {
    alias: 'spk',
    type: 'speech',
    syntax: 'auto | none | normal',
    compiler: (v) => v,
    values: ['auto:a', 'none:n', 'normal:n'],
  },
  'speak-as': {
    alias: 'spa',
    type: 'speech',
    syntax: 'normal | spell-out | digits | literal-punctuation | no-punctuation',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'speak-header': {
    alias: 'sph',
    type: 'speech',
    syntax: 'once | always',
    compiler: (v) => v,
    values: ['once:o', 'always:a'],
  },
  'speech-rate': {
    alias: 'sr',
    type: 'speech',
    syntax: '[normal | x-slow | slow | medium | fast | x-fast] | <number> | <percentage>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  src: {
    alias: 'src',
    type: 'font',
    syntax: '[<url> [format(<string>#)]? | local(<family-name>)]#',
    compiler: (v) => v,
    values: [],
  },
  'stop-color': { alias: 'sc', type: 'color', syntax: '<color>', compiler: (v) => v, values: [] },
  'stop-opacity': { alias: 'so', type: 'color', syntax: '<number-percentage>', compiler: (v) => v, values: [] },
  stress: { alias: 'stress', type: 'speech', syntax: '<number>', compiler: (v) => v, values: [] },
  'string-set': {
    alias: 'ss',
    type: 'layout',
    syntax: '[<custom-ident> <content-replacement>]# | none',
    compiler: (v) => v,
    values: ['none:n'],
  },
  stroke: { alias: 'stroke', type: 'paint', syntax: 'none | <color> | <url>', compiler: (v) => v, values: ['none:n'] },
  'stroke-dasharray': {
    alias: 'sda',
    type: 'svg',
    syntax: '[<length-percentage> | <number>]# | context-value',
    compiler: (v) => v,
    values: ['context-value'],
  },
  'stroke-dashoffset': {
    alias: 'sdo',
    type: 'svg',
    syntax: '<length-percentage> | <number> | context-value',
    compiler: (v) => v,
    values: ['context-value'],
  },
  'stroke-linecap': {
    alias: 'slc',
    type: 'svg',
    syntax: 'butt | round | square | context-value',
    compiler: (v) => v,
    values: ['butt:b', 'round:r', 'square:s'],
  },
  'stroke-linejoin': {
    alias: 'slj',
    type: 'svg',
    syntax: 'arcs | bevel | miter | miter-clip | round | context-value',
    compiler: (v) => v,
    values: ['bevel:b', 'miter:m', 'round:r'],
  },
  'stroke-miterlimit': {
    alias: 'sml',
    type: 'svg',
    syntax: '<number> | context-value',
    compiler: (v) => v,
    values: ['context-value'],
  },
  'stroke-opacity': {
    alias: 'so',
    type: 'svg',
    syntax: '<number-percentage> | context-value',
    compiler: (v) => v,
    values: ['context-value'],
  },
  'stroke-width': {
    alias: 'sw',
    type: 'svg',
    syntax: '[<length-percentage> | <number>] | context-value',
    compiler: (v) => v,
    values: ['context-value'],
  },
  style: {
    alias: 'style',
    type: 'font',
    syntax: 'normal | italic | oblique <angle>?',
    compiler: (v) => v,
    values: ['normal:n', 'italic:i'],
  },
  suffix: { alias: 'suffix', type: 'layout', syntax: '<symbol>', compiler: (v) => v, values: [] },
  'tab-size': { alias: 'ts', type: 'typography', syntax: '<number> | <length>', compiler: (v) => v, values: [] },
  'table-layout': {
    alias: 'tl',
    type: 'table',
    syntax: 'auto | fixed',
    compiler: (v) => v,
    values: ['auto:a', 'fixed:f'],
  },
  'text-align': {
    alias: 'ta',
    type: 'typography',
    syntax: 'start | end | left | right | center | justify | justify-all | match-parent',
    compiler: (v) => v,
    values: ['left:l', 'right:r', 'center:c', 'justify:j'],
  },
  'text-align-last': {
    alias: 'tal',
    type: 'typography',
    syntax: 'auto | start | end | left | right | center | justify',
    compiler: (v) => v,
    values: ['auto:a', 'left:l', 'center:c'],
  },
  'text-anchor': {
    alias: 'tan',
    type: 'svg',
    syntax: 'start | middle | end',
    compiler: (v) => v,
    values: ['start:s', 'middle:m', 'end:e'],
  },
  'text-autospace': {
    alias: 'tas',
    type: 'typography',
    syntax: 'normal | no-autospace',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'text-decoration': {
    alias: 'td',
    type: 'typography',
    syntax:
      "<'text-decoration-line'> || <'text-decoration-style'> || <'text-decoration-color'> || <'text-decoration-thickness'>",
    compiler: (v) => v,
    values: [],
  },
  'text-decoration-color': { alias: 'tdc', type: 'typography', syntax: '<color>', compiler: (v) => v, values: [] },
  'text-decoration-line': {
    alias: 'tdl',
    type: 'typography',
    syntax: 'none | [underline || overline || line-through || blink]',
    compiler: (v) => v,
    values: ['none:n', 'underline:u', 'overline:o', 'line-through:lt'],
  },
  'text-decoration-skip': {
    alias: 'tds',
    type: 'typography',
    syntax: 'none | [objects || spaces || leading-spaces || trailing-spaces]',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'text-decoration-skip-ink': {
    alias: 'tdsi',
    type: 'typography',
    syntax: 'auto | none',
    compiler: (v) => v,
    values: ['auto:a', 'none:n'],
  },
  'text-decoration-style': {
    alias: 'tds',
    type: 'typography',
    syntax: 'solid | double | dotted | dashed | wavy',
    compiler: (v) => v,
    values: ['solid:s', 'double:d', 'dotted:dt', 'dashed:ds', 'wavy:w'],
  },
  'text-decoration-thickness': {
    alias: 'tdt',
    type: 'typography',
    syntax: 'auto | from-font | <length>',
    compiler: (v) => v,
    values: ['auto:a', 'from-font:ff'],
  },
  'text-emphasis': {
    alias: 'te',
    type: 'typography',
    syntax: "<'text-emphasis-style'> || <'text-emphasis-color'>",
    compiler: (v) => v,
    values: [],
  },
  'text-emphasis-color': { alias: 'tec', type: 'typography', syntax: '<color>', compiler: (v) => v, values: [] },
  'text-emphasis-position': {
    alias: 'tep',
    type: 'typography',
    syntax: '[ [ before | after ] || [ over | under ] ]',
    compiler: (v) => v,
    values: [],
  },
  'text-emphasis-style': {
    alias: 'tes',
    type: 'typography',
    syntax: 'none | [ [ filled | open ] || [ dot | circle | double-circle | triangle | sesame | <string> ] ]',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'text-indent': {
    alias: 'ti',
    type: 'typography',
    syntax: '[<length-percentage>] && hanging? && each-line?',
    compiler: (v) => v,
    values: [],
  },
  'text-justify': {
    alias: 'tj',
    type: 'typography',
    syntax: 'auto | inter-character | inter-word | none',
    compiler: (v) => v,
    values: ['auto:a', 'none:n'],
  },
  'text-orientation': {
    alias: 'to',
    type: 'typography',
    syntax: 'mixed | upright | sideways',
    compiler: (v) => v,
    values: ['mixed:m', 'upright:u', 'sideways:s'],
  },
  'text-overflow': {
    alias: 'to',
    type: 'typography',
    syntax: '[clip | ellipsis | <string>]{1,2}',
    compiler: (v) => v,
    values: ['clip:c', 'ellipsis:e'],
  },
  'text-rendering': {
    alias: 'tr',
    type: 'typography',
    syntax: 'auto | optimizeSpeed | optimizeLegibility | geometricPrecision',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'text-shadow': {
    alias: 'ts',
    type: 'typography',
    syntax: 'none | <shadow>#',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'text-size-adjust': {
    alias: 'tsa',
    type: 'typography',
    syntax: 'none | auto | <percentage>',
    compiler: (v) => v,
    values: ['none:n', 'auto:a'],
  },
  'text-spacing-trim': {
    alias: 'tst',
    type: 'typography',
    syntax: 'normal | trim-start | trim-end | trim-both | space-trim',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'text-transform': {
    alias: 'tt',
    type: 'typography',
    syntax: 'none | capitalize | uppercase | lowercase | full-width | full-size-kana',
    compiler: (v) => v,
    values: ['none:n', 'capitalize:c', 'uppercase:u', 'lowercase:l'],
  },
  'text-underline-offset': {
    alias: 'tuo',
    type: 'typography',
    syntax: 'auto | <length-percentage>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'text-underline-position': {
    alias: 'tup',
    type: 'typography',
    syntax: 'auto | under | left | right | [under || [left | right]]',
    compiler: (v) => v,
    values: ['auto:a', 'under:u'],
  },
  'text-wrap': {
    alias: 'tw',
    type: 'typography',
    syntax: 'wrap | nowrap | balance | stable | pretty',
    compiler: (v) => v,
    values: ['wrap:w', 'nowrap:n', 'balance:b'],
  },
  'text-wrap-mode': {
    alias: 'twm',
    type: 'typography',
    syntax: 'wrap | nowrap',
    compiler: (v) => v,
    values: ['wrap:w', 'nowrap:n'],
  },
  'text-wrap-style': {
    alias: 'tws',
    type: 'typography',
    syntax: 'auto | balance | stable | pretty',
    compiler: (v) => v,
    values: ['auto:a', 'balance:b'],
  },
  'timeline-scope': {
    alias: 'ts',
    type: 'motion',
    syntax: 'auto | <custom-ident>#',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'timing-function': {
    alias: 'tf',
    type: 'motion',
    syntax: 'linear | ease | ease-in | ease-out | ease-in-out | cubic-bezier() | steps()',
    compiler: (v) => v,
    values: ['linear:l', 'ease:e'],
  },
  'touch-action': {
    alias: 'ta',
    type: 'ui',
    syntax: 'auto | none | [ [pan-x | pan-left | pan-right] || [pan-y | pan-up | pan-down] || pinch-zoom ]',
    compiler: (v) => v,
    values: ['auto:a', 'none:n'],
  },
  transform: {
    alias: 'trf',
    type: 'motion',
    syntax: 'none | <transform-list>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'transform-box': {
    alias: 'tfb',
    type: 'motion',
    syntax: 'content-box | border-box | fill-box | stroke-box | view-box',
    compiler: (v) => v,
    values: ['content-box:cb', 'border-box:bb'],
  },
  'transform-origin': {
    alias: 'tfo',
    type: 'motion',
    syntax: '<position> [<length>]?',
    compiler: (v) => v,
    values: [],
  },
  'transform-style': {
    alias: 'tfs',
    type: 'motion',
    syntax: 'flat | preserve-3d',
    compiler: (v) => v,
    values: ['flat:f', 'preserve-3d:p3d'],
  },
  transition: { alias: 'trans', type: 'motion', syntax: '<single-transition>#', compiler: (v) => v, values: [] },
  'transition-delay': { alias: 'td', type: 'motion', syntax: '<time>#', compiler: (v) => v, values: [] },
  'transition-duration': { alias: 'tdur', type: 'motion', syntax: '<time>#', compiler: (v) => v, values: [] },
  'transition-property': {
    alias: 'tp',
    type: 'motion',
    syntax: 'none | <single-transition-property>#',
    compiler: (v) => v,
    values: ['none:n', 'all:a'],
  },
  'transition-timing-function': {
    alias: 'ttf',
    type: 'motion',
    syntax: '<easing-function>#',
    compiler: (v) => v,
    values: [],
  },
  translate: {
    alias: 'trl',
    type: 'motion',
    syntax: 'none | <length-percentage> [<length-percentage> <length>?]?',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'turn-phrase': {
    alias: 'tp',
    type: 'typography',
    syntax: 'normal | <custom-ident> | <string>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'unicode-bidi': {
    alias: 'ub',
    type: 'typography',
    syntax: 'normal | embed | isolate | bidi-override | isolate-override | plaintext',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'unicode-range': { alias: 'ur', type: 'font', syntax: '<urange>', compiler: (v) => v, values: [] },
  'unicode-mode': { alias: 'um', type: 'font', syntax: 'normal', compiler: (v) => v, values: ['normal:n'] },
  'user-modify': {
    alias: 'um',
    type: 'ui',
    syntax: 'read-only | read-write | write-only',
    compiler: (v) => v,
    values: ['read-only:ro', 'read-write:rw'],
  },
  'user-select': {
    alias: 'us',
    type: 'ui',
    syntax: 'auto | text | none | contain | all',
    compiler: (v) => v,
    values: ['auto:a', 'none:n', 'text:t', 'all:a'],
  },
  'user-zoom': { alias: 'uz', type: 'ui', syntax: 'zoom | fixed', compiler: (v) => v, values: ['zoom:z', 'fixed:f'] },
  'vector-effect': {
    alias: 've',
    type: 'svg',
    syntax:
      'none | non-scaling-stroke | non-scaling-size | non-rotation | fixed-position | context-fill | context-stroke',
    compiler: (v) => v,
    values: ['none:n'],
  },
  'vertical-align': {
    alias: 'va',
    type: 'typography',
    syntax: 'baseline | sub | super | text-top | text-bottom | middle | top | bottom | <percentage> | <length>',
    compiler: (v) => v,
    values: ['baseline:b', 'middle:m', 'top:t', 'bottom:bt'],
  },
  'view-transition-name': {
    alias: 'vtn',
    type: 'layout',
    syntax: 'none | <custom-ident>',
    compiler: (v) => v,
    values: ['none:n'],
  },
  visibility: {
    alias: 'vis',
    type: 'layout',
    syntax: 'visible | hidden | collapse',
    compiler: (v) => v,
    values: ['visible:v', 'hidden:h', 'collapse:c'],
  },
  'voice-balance': {
    alias: 'vb',
    type: 'speech',
    syntax: '<number> | left | center | right | leftwards | rightwards',
    compiler: (v) => v,
    values: ['center:c'],
  },
  'voice-duration': { alias: 'vd', type: 'speech', syntax: 'auto | <time>', compiler: (v) => v, values: ['auto:a'] },
  'voice-family': {
    alias: 'vf',
    type: 'speech',
    syntax: '[[<voice-name> | <generic-voice>] [, [<voice-name> | <generic-voice>]]*]?',
    compiler: (v) => v,
    values: [],
  },
  'voice-pitch': {
    alias: 'vp',
    type: 'speech',
    syntax: '<frequency> && absolute? | [[x-low | low | medium | high | x-high] || [<frequency> || relative]]',
    compiler: (v) => v,
    values: ['medium:m'],
  },
  'voice-range': {
    alias: 'vr',
    type: 'speech',
    syntax: '<frequency> && absolute? | [[x-low | low | medium | high | x-high] || [<frequency> || relative]]',
    compiler: (v) => v,
    values: ['medium:m'],
  },
  'voice-rate': {
    alias: 'vr',
    type: 'speech',
    syntax: '[normal | slow | fast] || <percentage>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'voice-stress': {
    alias: 'vs',
    type: 'speech',
    syntax: 'normal | strong | moderate | none | reduced',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'voice-volume': {
    alias: 'vv',
    type: 'speech',
    syntax: 'silent | [[ x-soft | soft | medium | loud | x-loud ] || <decibel>]',
    compiler: (v) => v,
    values: ['silent:s', 'medium:m'],
  },
  'white-space': {
    alias: 'ws',
    type: 'typography',
    syntax: 'normal | pre | nowrap | pre-wrap | pre-line | break-spaces | trim-outer',
    compiler: (v) => v,
    values: ['normal:n', 'pre:p', 'nowrap:n', 'pre-wrap:pw'],
  },
  'white-space-collapse': {
    alias: 'wsc',
    type: 'typography',
    syntax: 'collapse | discard | preserve | preserve-breaks | preserve-spaces',
    compiler: (v) => v,
    values: ['collapse:c', 'preserve:p'],
  },
  widows: { alias: 'wid', type: 'layout', syntax: '<integer>', compiler: (v) => parseInt(v), values: [] },
  width: {
    alias: 'w',
    type: 'size',
    syntax: 'auto | <length-percentage> | min-content | max-content | fit-content(<length-percentage>) | <calc-size()>',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'will-change': {
    alias: 'wc',
    type: 'performance',
    syntax: 'auto | <animateable-feature>#',
    compiler: (v) => v,
    values: ['auto:a'],
  },
  'word-break': {
    alias: 'wb',
    type: 'typography',
    syntax: 'normal | break-all | keep-all | break-word | auto-phrase | auto-phrase-without-hanja',
    compiler: (v) => v,
    values: ['normal:n', 'break-all:ba', 'keep-all:ka'],
  },
  'word-spacing': {
    alias: 'wsp',
    type: 'typography',
    syntax: 'normal | <length-percentage>',
    compiler: (v) => v,
    values: ['normal:n'],
  },
  'word-wrap': {
    alias: 'ww',
    type: 'typography',
    syntax: 'normal | break-word',
    compiler: (v) => v,
    values: ['normal:n', 'break-word:bw'],
  },
  'writing-mode': {
    alias: 'wm',
    type: 'typography',
    syntax: 'horizontal-tb | vertical-rl | vertical-lr | sideways-rl | sideways-lr | sideways',
    compiler: (v) => v,
    values: ['horizontal-tb:htb', 'vertical-rl:vrl', 'vertical-lr:vlr'],
  },
  x: { alias: 'x', type: 'svg', syntax: '<length> | <percentage>', compiler: (v) => v, values: [] },
  y: { alias: 'y', type: 'svg', syntax: '<length> | <percentage>', compiler: (v) => v, values: [] },
  'z-index': {
    alias: 'zi',
    type: 'stacking',
    syntax: 'auto | <integer>',
    compiler: (v) => (v === 'auto' ? 'auto' : parseInt(v)),
    values: ['auto:a'],
  },
  zoom: { alias: 'z', type: 'ui', syntax: 'auto | <number> | <percentage>', compiler: (v) => v, values: ['auto:a'] },
};
