export const customStaticClassNames: { [key: string]: string } = {
  // ----------------------Border-Radius
  "x-radius-none":'border-radius:var(--x-radius-none,0px)',
  "x-radius-xxs":'border-radius:var(--x-radius-xxs,2px)',
  "x-radius-xs":'border-radius:var(--x-radius-xs,4px)',
  "x-radius-sm":'border-radius:var(--x-radius-sm,6px)',
  "x-radius-md":'border-radius:var(--x-radius-md,8px)',
  "x-radius-lg":'border-radius:var(--x-radius-lg,10px)',
  "x-radius-xl":'border-radius:var(--x-radius-xl,12px)',
  "x-radius-2xl":'border-radius:var(--x-radius-2xl,16px)',
  "x-radius-3xl":'border-radius:var(--x-radius-3xl,20px)',
  "x-radius-4xl":'border-radius:var(--x-radius-4xl,24px)',
  "x-radius-full":'border-radius:var(--x-radius-full,9999px)',
  // --------  end

  // --Padding/Spacing
  "x-padding-none":'padding:var(--x-padding-none,0px)',
  "x-padding-xxs":'padding:var(--x-padding-xxs,2px)',
  "x-padding-xs":'padding:var(--x-padding-xs,4px)',
  "x-padding-sm":'padding:var(--x-padding-sm,6px)',
  "x-padding-md":'padding:var(--x-padding-md,8px)',
  "x-padding-lg":'padding:var(--x-padding-lg,12px)',
  "x-padding-xl":'padding:var(--x-padding-xl,16px)',
  "x-padding-2xl":'padding:var(--x-padding-2xl,20px)',
  "x-padding-3xl":'padding:var(--x-padding-3xl,24px)',
  "x-padding-4xl":'padding:var(--x-padding-4xl,32px)',
  "x-padding-5xl":'padding:var(--x-padding-5xl,40px)',
  "x-padding-6xl":'padding:var(--x-padding-6xl,48px)',
  "x-padding-7xl":'padding:var(--x-padding-7xl,64px)',
  "x-padding-8xl":'padding:var(--x-padding-8xl,80px)',
  "x-padding-9xl":'padding:var(--x-padding-9xl,96px)',
  "x-padding-10xl":'padding:var(--x-padding-10xl,128px)',
  "x-padding-11xl":'padding:var(--x-padding-11xl,160px)',

  "x-padding-mobile":'padding:var(--x-padding-mobile,16px)',
  "x-container-padding-mobile":'padding:var(--x-container-padding-mobile,16px)',
  "x-padding-desktop":'padding:var(--x-padding-desktop,32px)',
  "x-container-padding-desktop":'padding:var(--x-container-padding-desktop,32px)',

  "x-spacing-none":'padding:var(--x-spacing-none,0px)',
  "x-spacing-xxs":'padding:var(--x-spacing-xxs,2px)',
  "x-spacing-xs":'padding:var(--x-spacing-xs,4px)',
  "x-spacing-sm":'padding:var(--x-spacing-sm,6px)',
  "x-spacing-md":'padding:var(--x-spacing-md,8px)',
  "x-spacing-lg":'padding:var(--x-spacing-lg,12px)',
  "x-spacing-xl":'padding:var(--x-spacing-xl,16px)',
  "x-spacing-2xl":'padding:var(--x-spacing-2xl,20px)',
  "x-spacing-3xl":'padding:var(--x-spacing-3xl,24px)',
  "x-spacing-4xl":'padding:var(--x-spacing-4xl,32px)',
  "x-spacing-5xl":'padding:var(--x-spacing-5xl,40px)',
  "x-spacing-6xl":'padding:var(--x-spacing-6xl,48px)',
  "x-spacing-7xl":'padding:var(--x-spacing-7xl,64px)',
  "x-spacing-8xl":'padding:var(--x-spacing-8xl,80px)',
  "x-spacing-9xl":'padding:var(--x-spacing-9xl,96px)',
  "x-spacing-10xl":'padding:var(--x-spacing-10xl,128px)',
  "x-spacing-11xl":'padding:var(--x-spacing-11xl,160px)',

  // ---Width
  "x-width-xxs":'width:var(--x-width-xxs,320px)',
  "x-width-xs":'width:var(--x-width-xs,384px)',
  "x-width-sm":'width:var(--x-width-sm,480px)',
  "x-width-md":'width:var(--x-width-md,560px)',
  "x-width-lg":'width:var(--x-width-lg,640px)',
  "x-width-xl":'width:var(--x-width-xl,768px)',
  "x-width-2xl":'width:var(--x-width-2xl,1024px)',
  "x-width-3xl":'width:var(--x-width-3xl,1280px)',
  "x-width-4xl":'width:var(--x-width-4xl,1440px)',
  "x-width-5xl":'width:var(--x-width-5xl,1600px)',
  "x-width-6xl":'width:var(--x-width-6xl,1920px)',

  "x-max-width-desktop":'max-width:var(--x-max-width-desktop,1280px)',
  "x-desktop-width-desktop":'width:var(--x-desktop-width-desktop,1280px)',
  "x-width-tablet":'width:var(--x-width-tablet,768px)',
  "x-max-width-tablet":'max-width:var(--x-max-width-tablet,768px)',
  "x-width-mobile":'width:var(--x-width-mobile,375px)',
  "x-max-width-mobile":'max-width:var(--x-max-width-mobile,375px)',
  "x-container-max-width-desktop":'max-width:var(--x-container-max-width-desktop,1280px)',
  "x-paragraph-max-width":'max-width:var(--x-paragraph-max-width,720px)',


  // ---old

  'x-flex-center': 'display:flex; justify-content:center;align-items:center',
  'x-inline-flex-center': 'display:inline-flex; justify-content:center;align-items:center',
  'x-grid-center': 'display:grid; justify-content:center;align-content:center',
  'x-inline-grid-center': 'display:inline-grid; justify-content:center;align-content:center',
  'x-absolute-center':"position:absolute;margin:auto;top:0;left:0;right:0;bottom:0;",
  'x-fixed-center':"position:fixed;margin:auto;top:0;left:0;right:0;bottom:0;",
  'x-sr-only':'position:absolute;overflow:hidden;clip-path:rect(0 0 0 0);height:1px;width:1px;margin:-1px;padding:0;border:0',



  'x-display-2xl': 'font-size:72px ; line-height:90px ; letter-spacing:-0.02em',
  'x-display-xxl': 'font-size:72px ; line-height:90px ; letter-spacing:-0.02em',
  'x-display-xl': 'font-size: 60px; line-height: 72px; letter-spacing:-0.02em',
  'x-display-lg': 'font-size:48px ; line-height: 60px; letter-spacing:-0.02em',
  'x-display-md': 'font-size: 36px; line-height: 44px; letter-spacing:-0.02em',
  'x-display-sm': 'font-size: 30px; line-height: 38px',
  'x-display-xs': 'font-size: 24px; line-height: 32px',

  'x-heading-2xl': 'font-size:72px ; line-height:90px ; letter-spacing:-0.02em',
  'x-heading-xxl': 'font-size:72px ; line-height:90px ; letter-spacing:-0.02em',
  'x-heading-xl': 'font-size: 60px; line-height: 72px; letter-spacing:-0.02em',
  'x-heading-lg': 'font-size:48px ; line-height: 60px; letter-spacing:-0.02em',
  'x-heading-md': 'font-size: 36px; line-height: 44px; letter-spacing:-0.02em',
  'x-heading-sm': 'font-size: 30px; line-height: 38px',
  'x-heading-xs': 'font-size: 24px; line-height: 32px',

  'x-h-2xl': 'font-size:72px ; line-height:90px ; letter-spacing:-0.02em',
  'x-h-xxl': 'font-size:72px ; line-height:90px ; letter-spacing:-0.02em',
  'x-h-xl': 'font-size: 60px; line-height: 72px; letter-spacing:-0.02em',
  'x-h-lg': 'font-size:48px ; line-height: 60px; letter-spacing:-0.02em',
  'x-h-md': 'font-size: 36px; line-height: 44px; letter-spacing:-0.02em',
  'x-h-sm': 'font-size: 30px; line-height: 38px',
  'x-h-xs': 'font-size: 24px; line-height: 32px',

  'x-text-xl': 'font-size:20px;line-height:30px',
  'x-text-lg': 'font-size:18px;line-height:28px',
  'x-text-md': 'font-size:16px;line-height:24px',
  'x-text-sm': 'font-size:14px;line-height:20px',
  'x-text-xs': 'font-size:12px;line-height:18px',

  't-xl': 'font-size:20px;line-height:30px',
  't-lg': 'font-size:18px;line-height:28px',
  't-md': 'font-size:16px;line-height:24px',
  't-sm': 'font-size:14px;line-height:20px',
  't-xs': 'font-size:12px;line-height:18px',

   'x-button-xxl':
    'display:inline-flex;justify-content:center;align-items:center;gap:8px;padding:16px 28px;border-radius:8px;box-sizing:border-box',
  'x-button-2xl':
    'display:inline-flex;justify-content:center;align-items:center;gap:8px;padding:16px 28px;border-radius:8px;box-sizing:border-box',
  'x-button-xl':
    'display:inline-flex;justify-content:center;align-items:center;gap:8px;padding:12px 20px;border-radius:8px;box-sizing:border-box',
  'x-button-lg':
    'display:inline-flex;justify-content:center;align-items:center;gap:8px;padding:10px 18px;border-radius:8px;box-sizing:border-box',
  'x-button-md':
    'display:inline-flex;justify-content:center;align-items:center;gap:8px;padding:10px 16px;border-radius:8px;box-sizing:border-box',
  'x-button-sm':
    'display:inline-flex;justify-content:center;align-items:center;gap:8px;padding:8px 14px;border-radius:8px;box-sizing:border-box',
  'x-button-xs':
    'display:inline-flex;justify-content:center;align-items:center;gap:8px;padding:8px 12px;border-radius:8px;box-sizing:border-box',

  'x-shadow-3xl': 'box-shadow:var(--x-shadow-3xl, 0px 32px 64px -12px rgba(16, 24, 40, 0.14))',
  'x-shadow-xxxl': 'box-shadow:var(--x-shadow-xxxl, 0px 32px 64px -12px rgba(16, 24, 40, 0.14))',
  'x-shadow-2xl': 'box-shadow:var(--x-shadow-2xl, 0px 24px 48px -12px rgba(16, 24, 40, 0.18))',
  'x-shadow-xxl': 'box-shadow:var(--x-shadow-xxl, 0px 24px 48px -12px rgba(16, 24, 40, 0.18))',
  'x-shadow-xl': 'box-shadow:var(--x-shadow-xl, 0px 20px 24px -4px rgba(16, 24, 40, 0.08), 0px 8px 8px -4px rgba(16, 24, 40, 0.03))',
  'x-shadow-lg': 'box-shadow:var(--x-shadow-lg, 0px 12px 16px -4px rgba(16, 24, 40, 0.08), 0px 4px 6px -2px rgba(16, 24, 40, 0.03))',
  'x-shadow-md': 'box-shadow:var(--x-shadow-md, 0px 4px 8px -2px rgba(16, 24, 40, 0.1), 0px 2px 4px -2px rgba(16, 24, 40, 0.06))',
  'x-shadow-sm': 'box-shadow:var(--x-shadow-sm, 0px 1px 3px rgba(16, 24, 40, 0.1), 0px 1px 2px rgba(16, 24, 40, 0.06))',
  'x-shadow-xs': 'box-shadow:var(--x-shadow-xs, 0px 1px 2px rgba(16, 24, 40, 0.05))',

  'x-ring-brand':'box-shadow:var(--x-ring-brand, 0px 0px 0px 4px rgba(158, 119, 237, 0.24))',
  'x-ring-gray':'box-shadow:var(--x-ring-gray, 0px 0px 0px 4px rgba(152, 162, 179, 0.14))',
  'x-ring-gray-secondary':'box-shadow:var(--x-ring-gray-secondary, 0px 0px 0px 4px rgba(152, 162, 179, 0.20))',
  'x-ring-error':'box-shadow:var(--x-ring-error, 0px 0px 0px 4px rgba(240, 68, 56, 0.24))',

  'x-ring-brand-shadow-xs':'box-shadow:var(--x-ring-brand-shadow-xs, 0px 1px 2px 0px rgba(16, 24, 40, 0.05), 0px 0px 0px 4px rgba(158, 119, 237, 0.24))',
  'x-ring-brand-shadow-sm':'box-shadow:var(--x-ring-brand-shadow-sm, 0px 1px 3px 0px rgba(16, 24, 40, 0.10), 0px 1px 2px 0px rgba(16, 24, 40, 0.06), 0px 0px 0px 4px rgba(158, 119, 237, 0.24))',
  'x-ring-brand-gray-xs':'box-shadow:var(--x-ring-brand-gray-xs, 0px 1px 2px 0px rgba(16, 24, 40, 0.05), 0px 0px 0px 4px rgba(152, 162, 179, 0.14))',
  'x-ring-brand-gray-sm':'box-shadow:var(--x-ring-brand-gray-sm, 0px 1px 3px 0px rgba(16, 24, 40, 0.10), 0px 1px 2px 0px rgba(16, 24, 40, 0.06), 0px 0px 0px 4px rgba(152, 162, 179, 0.14))',
  'x-ring-brand-error-xs':'box-shadow:var(--x-ring-brand-error-xs, 0px 1px 2px 0px rgba(16, 24, 40, 0.05), 0px 0px 0px 4px rgba(240, 68, 56, 0.24))',

  // Blur
  'x-blur-sm':'backdrop-filter: var(--x-blur-sm,blur(4px))',
  'x-blur-md':'backdrop-filter: var(--x-blur-md,blur(8px))',
  'x-blur-lg':'backdrop-filter: var(--x-blur-lg,blur(12px))',
  'x-blur-xl':'backdrop-filter: var(--x-blur-xl,blur(20px))',

  // ------from pre-builds
  'x-screen-root':`overflow:hidden;position:relative`,
  'x-screen':`transition-duration:var(--x-screen-transition-duration,0.35s);position:absolute;transition-timing-function:var(--x-screen-transition-timing-function,ease-in-out);transition-property:transform ,height ,width;transform:translateY(0px);width:var(--x-screen-width,100%);height:var(--x-screen-height,100%)`,
  'x-screen-active':`transform:translate(0)`,
  'x-screen-up':`z-index:2;top:0;left:0;transform:translateY(var(--t-up));--t-up:calc(0% - var(--x-screen-offset,100%))`,
  'x-screen-down':`z-index:3;bottom:0;left:0;transform:translateY(var(--t-down));--t-down:calc(var(--x-screen-offset,100%) - 0%)`,
  'x-screen-left':`z-index:4;transform:translateX(var(--t-left));--t-left:calc(0% - var(--x-screen-offset,100%))`,
  'x-screen-right':`z-index:5;top:0;right:0;transform:translateX(var(--t-right));--t-right:calc(var(--x-screen-offset,100%) - 0%)`,
  'x-section':`width: var(--x-section-width,100%);padding:var(--x-section-padding,20px);height: var(--x-section-height,auto)`, 
  'x-section-spacious':`padding:var(--x-section-padding,80px)`,
  'x-container':`width: 100%;max-width: var(--x-container-width,1200px);margin:0 auto;padding:var(--x-container-padding,16px)`,   
  'x-container-fluid':`--x-container-width:100%`,
  'x-container-narrow':`--x-container-width:800px`,
  'x-row':`display:flex;flex-wrap:wrap;gap:var(--x-row-gap,16px);margin:calc(var(--x-row-gap,16px) / -2);box-sizing:border-box;flex-grow:1`,
  'x-row-no-wrap':`flex-wrap:nowrap`,
  'x-row-center':`justify-content:center`,
  'x-col':`display:flex;flex-wrap:wrap;gap:var(--x-col-gap,16px);margin:calc(var(--x-col-gap,16px) / -2);box-sizing:border-box;flex-grow:1`,
  'x-col-no-wrap':`flex-wrap:nowrap`,
  'x-col-center':`justify-content:center`,
  'x-col-full':`flex-grow:1`,
  'x-box':`background-color:var(--x-box-bg,#ffffff);padding:var(--x-box-padding,16px);border-radius:var(--x-box-border-radius,8px);border:var(--x-box-border,1px solid #e0e0e0);box-sizing:border-box`,
  'x-box-shadow':`box-shadow:var(--x-box-shadow,0px 2px 8px rgba(0, 0, 0, 0.13))`,
  
  'x-card':`background-color:var(--x-card-bg,#ffffff);padding:var(--x-card-padding,24px);border-radius:var(--x-card-border-radius,12px);box-shadow:var(--x-card-shadow,0px 4px 12px rgba(0, 0, 0, 0.13));box-sizing:border-box;transition:transform 0.3s ease, box-shadow 0.3s ease;color:var(--x-card-color,#000000)`,
  'x-card-interactive':`cursor:pointer`,
  'x-card-dark':`--x-card-bg:#1a1a1a;--x-card-shadow:0px 4px 12px rgba(0, 0, 0, 0.20);--x-card-color:#ffffff`,
  
  'x-divider':`display:block;border-top-width:var(--x-divider-width,1px);border-top-color:var(--x-divider-color,#808080);border-top-style:var(--x-divider-style,solid);box-sizing:border-box;`,
  'x-divider-text':`display:flex;align-items:center;gap:12px;`,
  'x-divider-text-addon':`display:flex;content:"";flex:1;background-color: var(--x-divider-color,#83859C);height:var(--x-divider-width,1px);`,

  'x-arrow':`border-style:solid;border-color:var(--x-arrow-color,#2B2B43);border-width:0px 3px 3px 0;display:inline-block;padding:3px;`,
  'x-arrow-up':`transform:rotate(-135deg);-webkit-transform:rotate(-135deg);`,
  'x-arrow-down':`transform:rotate(45deg);-webkit-transform:rotate(45deg);`,
  'x-arrow-left':`transform:rotate(135deg);-webkit-transform:rotate(135deg);`,
  'x-arrow-right':`transform:rotate(-45deg);-webkit-transform:rotate(-45deg);`, 
   
  
  'x-colorize-dark':'background:#0f0f0f;color:#e3e3e3',
  'x-clip-menu':'clip-path: polygon(0% 10%,100% 10%,100% 20%,0% 20%,0% 45%,100% 45%,100% 55%,0% 55%,0% 80%,100% 80%,100% 90%,0% 90%);',
  'x-clip-message':'clip-path: polygon(0% 0%,100% 0%,100% 80%,60% 80%,50% 100%,40% 80%,0% 80%);',
  'x-clip-star':'clip-path: polygon(50% 0%,61% 35%,98% 35%,68% 57%,79% 91%,50% 70%,21% 91%,32% 57%,2% 35%,39% 35%);',
  'x-clip-close': 'clip-path: polygon(20% 0%, 0% 20%, 30% 50%, 0% 80%, 20% 100%, 50% 70%, 80% 100%, 100% 80%, 70% 50%, 100% 20%, 80% 0%, 50% 30%)',
  'x-clip-plus': 'clip-path: polygon(40% 0%,60% 0%,60% 40%,100% 40%,100% 60%,60% 60%,60% 100%,40% 100%,40% 60%,0% 60%,0% 40%,40% 40%);',
  'x-colorize-light':'background:#e3e3e3;color:rgba(0,0,0,0.8)',
  'flex-center':'display:flex;align-items:center;justify-content:center',
  'absolute-center':'position:absolute;top:0;right:0;left:0;bottom:0:margin:auto',
  'sr-only':'position:absolute;overflow:hidden;clip:rect(0 0 0 0);height:1px;width:1px;margin:-1px;padding:0;border:0',
};
