export const staticClassNamesAlias: { [key: string]: string } = {
  'acc': 'align-content: center',
  'ace': 'align-content:end',
  'acfe': 'align-content: flex-end',
  'acfs': 'align-content: flex-start',
  'acs2': 'align-content: stretch',
  'acs': 'align-content: start',
  'acs/stretch': 'align-content: stretch',
  'acs/start': 'align-content: start',
  'acsa': 'align-content: space-around',
  'acsb': 'align-content: space-between',
  'acse': 'align-content: space-evenly',
  'acst': 'align-content: stretch',
  'ada': 'animation-direction: alternate',
  'adar': 'animation-direction: alternate-reverse',
  'adn': 'animation-direction: normal',
  'adnl': 'animation-direction: normal',
  'adr': 'animation-direction: reverse',
  'afmb2': 'animation-fill-mode: both',
  'afmb': 'animation-fill-mode: backwards',
  'afmb/both': 'animation-fill-mode: both',
  'afmb/backward': 'animation-fill-mode: backwards',
  'afmbo': 'animation-fill-mode: both',
  'afmf': 'animation-fill-mode: forwards',
  'afmn': 'animation-fill-mode: none',
  'aib': 'align-items: baseline',
  'aic': 'align-items: center',
  'aici': 'animation-iteration-count: infinite',
  'aife': 'align-items: flex-end',
  'aifs': 'align-items: flex-start',
  'ais': 'align-items: stretch',
  'an': 'appearance:none',
  'ann': 'animation-name: none',
  'apsp': 'animation-play-state: paused',
  'apsr': 'animation-play-state: running',
  'ara': 'aspect-ratio: auto',
  'asa': 'align-self: auto',
  'asb': 'align-self: baseline',
  'asc': 'align-self: center',
  'asfe': 'align-self: flex-end',
  'asfs': 'align-self: flex-start',
  'ass': 'align-self: stretch',
  'atfe': 'animation-timing-function: ease',
  'atfei': 'animation-timing-function: ease-in',
  'atfeio': 'animation-timing-function: ease-in-out',
  'atfeo': 'animation-timing-function: ease-out',
  'atfl': 'animation-timing-function: linear',
  'atfse': 'animation-timing-function: step-end',
  'atfss': 'animation-timing-function: step-start',
  'ba': 'bottom: auto',
  'baa2': 'break-after: avoid',
  'baa3': 'break-after: always',
  'baa': 'break-after: auto',
  'baa/avoid': 'break-after: avoid',
  'baa/always': 'break-after: always',
  'baa/auto': 'break-after: auto',
  'baac': 'break-after: avoid-column',
  'baal': 'break-after: always',
  'baap': 'break-after: avoid-page',
  'baav': 'break-after: avoid',
  'bab2': 'box-align: baseline',
  'bab': 'box-align: before',
  'bab/baseline': 'box-align: baseline',
  'bab/before': 'box-align: before',
  'babl': 'box-align: baseline',
  'bac': 'break-after: column',
  'baf': 'box-align: after',
  'bal': 'break-after: left',
  'bam': 'box-align: middle',
  'bap': 'break-after: page',
  'bar': 'break-after: right',
  'bas': 'box-align: stretch',
  'bba2': 'break-before: avoid',
  'bba3': 'break-before: always',
  'bba': 'break-before: auto',
  'bba/avoid': 'break-before: avoid',
  'bba/always': 'break-before: always',
  'bba/auto': 'break-before: auto',
  'bbac': 'break-before: avoid-column',
  'bbal': 'break-before: always',
  'bbap': 'break-before: avoid-page',
  'bbav': 'break-before: avoid',
  'bbc': 'break-before: column',
  'bbl': 'break-before: left',
  'bbn': 'border-bottom:none',
  'bbp': 'break-before: page',
  'bbr': 'break-before: right',
  'bbsd2': 'border-bottom-style: double',
  'bbsd3': 'border-bottom-style: dotted',
  'bbsd': 'border-bottom-style: dashed',
  'bbsd/double': 'border-bottom-style: double',
  'bbsd/dotted': 'border-bottom-style: dotted',
  'bbsd/dashed': 'border-bottom-style: dashed',
  'bbsdb': 'border-bottom-style: double',
  'bbsds': 'border-bottom-style: dashed',
  'bbsdt': 'border-bottom-style: dotted',
  'bbsg': 'border-bottom-style: groove',
  'bbsh': 'border-bottom-style: hidden',
  'bbsi': 'border-bottom-style: inset',
  'bbsn': 'border-bottom-style: none',
  'bbso': 'border-bottom-style: outset',
  'bbsr': 'border-bottom-style: ridge',
  'bbss': 'border-bottom-style: solid',
  'bbwa': 'border-bottom-width: auto',
 'bbwm': 'border-bottom-width: medium',
  'bbwt2': 'border-bottom-width: thin',
  'bbwt': 'border-bottom-width: thick',
  'bbwt/thin': 'border-bottom-width: thin',
  'bbwt/thick': 'border-bottom-width: thick',
  'bbwtn': 'border-bottom-width: thin',
  'bcc': 'border-collapse: collapse',
 'bcn': 'border-color:none',
  'bcs': 'border-collapse: separate',
  'bdbc': 'box-decoration-break: clone',
  'bdbs': 'box-decoration-break: slice',
 'bfn': 'backdrop-filter:none',
  'bgaf': 'background-attachment: fixed',
  'bgal': 'background-attachment: local',
  'bgas': 'background-attachment: scroll',
  'bgbmc': 'background-blend-mode: color',
  'bgbmcb': 'background-blend-mode: color-burn',
  'bgbmcd': 'background-blend-mode: color-dodge',
  'bgbmd2': 'background-blend-mode: difference',
  'bgbmd/difference': 'background-blend-mode: difference',
  'bgbmd': 'background-blend-mode: darken',
  'bgbmd/darken': 'background-blend-mode: darken',
  'bgbmdf': 'background-blend-mode: difference',
  'bgbme': 'background-blend-mode: exclusion',
  'bgbmh': 'background-blend-mode: hue',
  'bgbml2': 'background-blend-mode: luminosity',
  'bgbml': 'background-blend-mode: lighten',
  'bgbml/luminosity': 'background-blend-mode: luminosity',
  'bgbml/lighteb': 'background-blend-mode: lighten',
  'bgbmlu': 'background-blend-mode: luminosity',
  'bgbmm': 'background-blend-mode: multiply',
  'bgbmn': 'background-blend-mode: normal',
  'bgbmo': 'background-blend-mode: overlay',
  'bgbms2': 'background-blend-mode: saturation',
  'bgbms': 'background-blend-mode: screen',
  'bgbms/saturation': 'background-blend-mode: saturation',
  'bgbms/screen': 'background-blend-mode: screen',
  'bgbmsa': 'background-blend-mode: saturation',
  'bgcbb': 'background-clip: border-box',
  'bgccb': 'background-clip: content-box',
 'bgcn': 'background-color:none',
  'bgcpb': 'background-clip: padding-box',
  'bgin': 'background-image: none',
  'bgn': 'background:none',
  'bgnr': 'background-repeat: no-repeat',
  'bgobb': 'background-origin: border-box',
  'bgocb': 'background-origin: content-box',
 'bgopb': 'background-origin: padding-box',
  'bgpb': 'background-position:bottom',
  'bgpbc': 'background-position:bottom center',
  'bgpbl': 'background-position:bottom left',
  'bgpbr': 'background-position:bottom right',
  'bgpc': 'background-position: center ',
  'bgpcb': 'background-position: center bottom ',
  'bgpcc': 'background-position: center center',
  'bgpct': 'background-position: center top ',
  'bgpl': 'background-position: left ',
  'bgplb': 'background-position: left bottom ',
  'bgplc': 'background-position: left center ',
  'bgplt': 'background-position: left top',
  'bgpr': 'background-position: right',
  'bgprb': 'background-position: right bottom',
  'bgprc': 'background-position: right center',
  'bgprt': 'background-position: right top',
  'bgpt': 'background-position: top',
  'bgptc': 'background-position: top center',
  'bgptl': 'background-position: top left',
  'bgptr': 'background-position: top right',
  'bgpxc': 'background-position-x: center',
  'bgpxl': 'background-position-x: left',
  'bgpxr': 'background-position-x: right',
  'bgpyb': 'background-position-y: bottom',
  'bgpyc': 'background-position-y: center',
  'bgpyt': 'background-position-y: top',
  'bgrn': 'background-repeat: no-repeat',
  'bgrnr': 'background-repeat: repeat no-repeat',
  'bgrr': 'background-repeat: repeat',
  'bgrrn': 'background-repeat: repeat no-repeat',
  'bgrrnr': 'background-repeat: repeat no-repeat',
  'bgrro': 'background-repeat: round',
  'bgrrx': 'background-repeat: repeat-x',
  'bgrry': 'background-repeat: repeat-y',
  'bgrs': 'background-repeat: space',
  'bgrx': 'background-repeat: repeat-x',
  'bgry': 'background-repeat: repeat-y',
  'bgsa': 'background-size: auto',
  'bgsc2': 'background-size:contain',
  'bgsc': 'background-size: cover',
  'bgsc/contain': 'background-size:contain',
  'bgsc/cover': 'background-size: cover',
  'bgscon': 'background-size: contain',
  'bia2': 'break-inside: avoid',
  'bia': 'break-inside: auto',
  'bia/avoid': 'break-inside: avoid',
  'bia/auto': 'break-inside: auto',
  'biac': 'break-inside: avoid-column',
  'biap': 'break-inside: avoid-page',
  'biav': 'break-inside: avoid',
  'biesd2': 'border-inline-end-style: double',
  'biesd3': 'border-inline-end-style: dotted',
  'biesd': 'border-inline-end-style: dashed',
  'biesd/double': 'border-inline-end-style: double',
  'biesd/dotted': 'border-inline-end-style: dotted',
  'biesd/dashed': 'border-inline-end-style: dashed',
  'biesdb': 'border-inline-end-style: double',
  'biesds': 'border-inline-end-style: dashed',
  'biesdt': 'border-inline-end-style: dotted',
  'biesg': 'border-inline-end-style: groove',
  'biesh': 'border-inline-end-style: hidden',
  'biesi': 'border-inline-end-style: inset',
  'biesn': 'border-inline-end-style: none',
  'bieso': 'border-inline-end-style: outset',
  'biesr': 'border-inline-end-style: ridge',
  'biess': 'border-inline-end-style: solid',
  // 'bir2': 'border-image-repeat: repeat',
  'birr': 'border-image-repeat: repeat',
  'birro': 'border-image-repeat: round',
  'birr2': 'border-image-repeat: round',
  'birr/repeat': 'border-image-repeat: repeat',
  'birr/round': 'border-image-repeat: round',
  'birs2': 'border-image-repeat: stretch',
  'birs': 'border-image-repeat: space',
  'birs/stretch': 'border-image-repeat: stretch',
  'birs/space': 'border-image-repeat: space',
  'birsth': 'border-image-repeat: stretch',
  'bisd2': 'border-inline-style: double',
  'bisd3': 'border-inline-style: dotted',
  'bisd': 'border-inline-style: dashed',
  'bisd/double': 'border-inline-style: double',
  'bisd/dotted': 'border-inline-style: dotted',
  'bisd/dashed': 'border-inline-style: dashed',
  'bisdb': 'border-inline-style: double',
  'bisds': 'border-inline-style: dashed',
  'bisdt': 'border-inline-style: dotted',
  'bisg': 'border-inline-style: groove',
  'bish': 'border-inline-style: hidden',
  'bisi': 'border-inline-style: inset',
  'bisn2': 'border-image-source: none',
  'bisn/source': 'border-image-source: none',
  'bisn/image-source': 'border-image-source: none',
  'bisn': 'border-inline-style: none',
  'bisn/inline-style': 'border-inline-style: none',
  'bisn/style': 'border-inline-style: none',
  'bisno': 'border-image-source: none',
  'biso': 'border-inline-style: outset',
  'bisr': 'border-inline-style: ridge',
  'biss': 'border-inline-style: solid',
  'bissd2': 'border-inline-start-style: double',
  'bissd3': 'border-inline-start-style: dotted',
  'bissd': 'border-inline-start-style: dashed',
  'bissd/double': 'border-inline-start-style: double',
  'bissd/dotted': 'border-inline-start-style: dotted',
  'bissd/dashed': 'border-inline-start-style: dashed',
  'bissdb': 'border-inline-start-style: double',
  'bissds': 'border-inline-start-style: dashed',
  'bissdt': 'border-inline-start-style: dotted',
  'bissg': 'border-inline-start-style: groove',
  'bissh': 'border-inline-start-style: hidden',
  'bissi': 'border-inline-start-style: inset',
  'bissn': 'border-inline-start-style: none',
  'bisso': 'border-inline-start-style: outset',
  'bissr': 'border-inline-start-style: ridge',
  'bisss': 'border-inline-start-style: solid',
  'blcn': 'border-left-color: none',
  'bln': 'border-left:none',
  'blsd2': 'border-left-style: double',
  'blsd3': 'border-left-style: dotted',
  'blsd': 'border-left-style: dashed',
  'blsd/double': 'border-left-style: double',
  'blsd/dotted': 'border-left-style: dotted',
  'blsd/dashed': 'border-left-style: dashed',
  'blsdb': 'border-left-style: double',
  'blsds': 'border-left-style: dashed',
  'blsdt': 'border-left-style: dotted',
  'blsg': 'border-left-style: groove',
  'blsh': 'border-left-style: hidden',
  'blsi': 'border-left-style: inset',
  'blsn': 'border-left-style: none',
  'blso': 'border-left-style: outset',
  'blsr': 'border-left-style: ridge',
  'blss': 'border-left-style: solid',
  'blwa': 'border-left-width: auto',
 'blwm': 'border-left-width: medium',
  'blwt2': 'border-left-width: thin',
  'blwt': 'border-left-width: thick',
  'blwt/thin': 'border-left-width: thin',
  'blwt/thick': 'border-left-width: thick',
  'blwtn': 'border-left-width: thin',
  'bn': 'border:none',
  'brcn': 'border-right-color: none',
  'brn': 'border-radius:none',
  'brsd2': 'border-right-style: double',
  'brsd3': 'border-right-style: dotted',
  'brsd': 'border-right-style: dashed',
  'brsd/double': 'border-right-style: double',
  'brsd/dotted': 'border-right-style: dotted',
  'brsd/dashed': 'border-right-style: dashed',
  'brsdb': 'border-right-style: double',
  'brsds': 'border-right-style: dashed',
  'brsdt': 'border-right-style: dotted',
  'brsg': 'border-right-style: groove',
  'brsh': 'border-right-style: hidden',
  'brsi': 'border-right-style: inset',
  'brsn': 'border-right-style: none',
  'brso': 'border-right-style: outset',
  'brsr': 'border-right-style: ridge',
  'brss': 'border-right-style: solid',
  'brtn': 'border-right:none',
  'brwa': 'border-right-width: auto',
 'brwm': 'border-right-width: medium',
  'brwt2': 'border-right-width: thin',
  'brwt': 'border-right-width: thick',
  'brwt/thin': 'border-right-width: thin',
  'brwt/thick': 'border-right-width: thick',
  'brwtn': 'border-right-width: thin',
  'bsbb': 'box-sizing: border-box',
  'bscb': 'box-sizing: content-box',
  'bsd2': 'border-style: double',
  'bsd3': 'border-style: dotted',
  'bsd': 'border-style: dashed',
  'bsd/double': 'border-style: double',
  'bsd/dotted': 'border-style: dotted',
  'bsd/dashed': 'border-style: dashed',
  'bsdb': 'border-style: double',
  'bsds': 'border-style: dashed',
  'bsdt': 'border-style: dotted',
  'bsg': 'border-style: groove',
  'bsh': 'border-style: hidden',
 'bsi': 'border-style: inset',
 'bsi/inset': 'border-style: inset',
 'bsn': 'border-style: none',
  'bso': 'border-style: outset',
  'bspb': 'box-sizing: padding-box',
  'bsr': 'border-style: ridge',
  'bss': 'border-style: solid',
  'btcn': 'border-top-color: none',
  'btma': 'bottom: auto',
  'btno': 'border-top:none',
  'btsd2': 'border-top-style: double',
  'btsd3': 'border-top-style: dotted',
  'btsd': 'border-top-style: dashed',
   'btsd/double': 'border-top-style: double',
  'btsd/dotted': 'border-top-style: dotted',
  'btsd/dashed': 'border-top-style: dashed',
  'btsdb': 'border-top-style: double',
  'btsds': 'border-top-style: dashed',
  'btsdt': 'border-top-style: dotted',
  'btsg': 'border-top-style: groove',
  'btsh': 'border-top-style: hidden',
  'btsi': 'border-top-style: inset',
  'btsn': 'border-top-style: none',
  'btso': 'border-top-style: outset',
  'btsr': 'border-top-style: ridge',
  'btss': 'border-top-style: solid',
  'btwa': 'border-top-width: auto',
 'btwm': 'border-top-width: medium',
  'btwt2': 'border-top-width: thin',
  'btwt': 'border-top-width: thick',
  'btwt/thin': 'border-top-width: thin',
  'btwt/thick': 'border-top-width: thick',
  'btwtn': 'border-top-width: thin',
  'bvh': 'backface-visibility: hidden',
  'bvv': 'backface-visibility: visible',
  'bwa': 'border-width: auto',
 'bwm': 'border-width: medium',
  'bwt2': 'border-width: thin',
  'bwt': 'border-width: thick',
  'bwt/thin': 'border-width: thin',
  'bwt/thick': 'border-width: thick',
  'bwtn': 'border-width: thin',
  'bxsn': 'box-shadow: none',
  'ca2': 'cursor: alias',
  'ca3': 'clip: auto',
  'ca': 'cursor: auto',
  'ca/alias': 'cursor: alias',
  'ca/clip': 'clip: auto',
  'ca/auto': 'cursor: auto',
  'ca/cursor': 'cursor: auto',
  'cab2': 'clear-after: bottom',
  'cab': 'clear-after: both',
  'cab/bottom': 'clear-after: bottom',
  'cab/both': 'clear-after: both',
  'cabtm': 'clear-after: bottom',
  'cad': 'clear-after: descendants',
  'cae': 'clear-after: end',
  'cai': 'clear-after: inside',
  'cal': 'cursor: alias',
  'can': 'clear-after: none',
  'cao': 'clear-after: outside',
  'car': 'clear-after: right',
  'cas2': 'clear-after: start',
  'cas/after': 'clear-after: start',
  'cas/clear': 'clear-after: start',
  'cas': 'cursor: all-scroll',
  'cas/cursor': 'cursor: all-scroll',
  'cast': 'clear-after: start',
  'cat': 'clear-after: top',
  'cb': 'clear: both',
  'cc': 'cursor: copy',
  'cca': 'column-count: auto',
  'ccc': 'color:currentColor',
  'cch': 'cursor: crosshair',
  'ccl': 'cursor: cell',
  'ccm': 'cursor: context-menu',
  'ccr': 'cursor: col-resize',
  'cd': 'cursor: default',
  'cer': 'cursor: e-resize',
  'cewr': 'cursor: ew-resize',
  'cfa': 'column-fill: auto',
  'cfb': 'column-fill: balance',
  'cgnl': 'column-gap: normal',
  'ch': 'cursor: help',
  'ci2': 'content: icon',
 'ci/icon': 'content: icon',
 'ci/content': 'content: icon',
  'cili': 'counter-increment: list-item',
  'cin': 'counter-increment: none',
  'cl': 'clear: left',
  'cla': 'clip: auto',
  'cm': 'cursor: move',
  'cn2': 'cursor: none',
  'cn3': 'content: none',
  'cn4': 'content: normal',
  'cn': 'clear: none',
   'cn/cursor': 'cursor: none',
  'cn/content': 'content: none',
  'cn/normal': 'content: normal',
  'cn/clear': 'clear: none',
  'cna': 'cursor: not-allowed',
  'cncq': 'content: no-close-quote',
  'cnd': 'cursor: no-drop',
  'cner': 'cursor: ne-resize',
  'cneswr': 'cursor: nesw-resize',
  'cnone': 'cursor: none',
  'cnoq': 'content: no-open-quote',
  'cnr2': 'cursor: ns-resize',
  'cnr3': 'cursor: nw-resize',
  'cnr4': 'cursor: nwse-resize',
  'cnr5': 'cursor: nesw-resize',
  'cnr6': 'cursor: nesw-resize',
  'cnr7': 'cursor: ne-resize',
  'cnr8': 'cursor: ne-resize',
  'cnr': 'cursor: n-resize',
  'cnr/ns': 'cursor: ns-resize',
  'cnr/nw': 'cursor: nw-resize',
  'cnr/nwse': 'cursor: nwse-resize',
  'cnr/nesw': 'cursor: nesw-resize',
  'cnr/ne': 'cursor: ne-resize',
  'cnr/n': 'cursor: n-resize',
  'cnsr': 'cursor: ns-resize',
  'cnwr': 'cursor: nw-resize',
  'cnwser': 'cursor: nwse-resize',
  'con': 'content:" "',
  'concq': 'content: close-quote',
  'ccq': 'content: close-quote',
  'coni': 'content: icon',
  'conn': 'content: none',
  'conncq': 'content: no-close-quote',
  'connl': 'content: normal',
  'connoq': 'content: no-open-quote',
  'coq': 'content: open-quote',
  'cp2': 'cursor: progress',
  'cp': 'cursor: pointer',
  'cp/progress': 'cursor: progress',
  'cp/pointer': 'cursor: pointer',
  'cpbb': 'clip-path: border-box',
  'cpcb': 'clip-path: content-box',
  'cpfb': 'clip-path: fill-box',
  'cpg': 'cursor: progress',
  'cpmb': 'clip-path: margin-box',
  'cpn': 'clip-path: none',
  'cppb': 'clip-path: padding-box',
  'cpsb': 'clip-path: stroke-box',
  'cpvb': 'clip-path: view-box',
  'cr': 'clear: right',
  'crli': 'counter-reset: list-item',
  'crn': 'counter-reset: none',
  'crr': 'cursor: row-resize',
  'crsd2': 'column-rule-style: double',
  'crsd3': 'column-rule-style: dotted',
  'crsd': 'column-rule-style: dashed',
  'crsd/double': 'column-rule-style: double',
  'crsd/dotted': 'column-rule-style: dotted',
  'crsd/dashed': 'column-rule-style: dashed',
  'crsdb': 'column-rule-style: double',
  'crsds': 'column-rule-style: dashed',
  'crsdt': 'column-rule-style: dotted',
  'crsg': 'column-rule-style: groove',
  'crsh': 'column-rule-style: hidden',
  'crsi': 'column-rule-style: inset',
  'crsn': 'column-rule-style: none',
  'crso': 'column-rule-style: outset',
  'crsr': 'column-rule-style: ridge',
  'crss': 'column-rule-style: solid',
  'crwm': 'column-rule-width: medium',
  'crwt2': 'column-rule-width: thin',
  'crwt': 'column-rule-width: thick',
  'crwt/thin': 'column-rule-width: thin',
  'crwt/thick': 'column-rule-width: thick',
  'crwtn': 'column-rule-width: thin',
  'csa': 'column-span: all',
  'csbtm': 'caption-side: bottom',
  'cser': 'cursor: se-resize',
  'csn': 'column-span: none',
  'csr2': 'cursor: sw-resize',
  'csr3': 'cursor: se-resize',
  'csr': 'cursor: s-resize',
   'csr/sw': 'cursor: sw-resize',
  'csr/se': 'cursor: se-resize',
  'csr/s': 'cursor: s-resize',
  'cst': 'caption-side: top',
  'cswr': 'cursor: sw-resize',
  'ct': 'cursor: text',
  'cvt': 'cursor: vertical-text',
  'cw': 'cursor: wait',
  'cwa': 'column-width: auto',
  'cwr': 'cursor: w-resize',
  'czi': 'cursor: zoom-in',
  'czo': 'cursor: zoom-out',
  'db': 'display: block',
  'dc2': 'display: compact',
  'dc': 'display: container',
  'dc/compact': 'display: compact',
  'dc/container': 'display: container',
  'dcp': 'display: compact',
  'df': 'display: flex',
  'dg': 'display: grid',
  'di': 'display: inline',
  'dib': 'display: inline-block',
  'dif': 'display: inline-flex',
  'dig': 'display: inline-grid',
  'dit': 'display: inline-table',
  'dli': 'display: list-item',
  'dn': 'display: none',
  'dri': 'display: run-in',
  'dt': 'display: table',
  'dtc2': 'display: table-caption',
  'dtc3': 'display: table-cell',
  'dtc': 'display: table-column',
  'dtc/caption': 'display: table-caption',
  'dtc/cell': 'display: table-cell',
  'dtc/column': 'display: table-column',
  'dtcg': 'display: table-column-group',
  'dtcl': 'display: table-cell',
  'dtcp': 'display: table-caption',
  'dtfg': 'display: table-footer-group',
  'dthg': 'display: table-header-group',
  'dtr': 'display: table-row',
  'dtrg': 'display: table-row-group',
  'ech': 'empty-cells: hide',
  'ecs': 'empty-cells: show',
  'fa': 'flex: auto',
  'fba': 'flex-basis: auto',
  'fbc': 'flex-basis:content',
 'fbmc': 'flex-basis:min-content',
  'fbxc': 'flex-basis:max-content',
  'fdc': 'flex-direction: column',
  'fdcr': 'flex-direction: column-reverse',
  'fdr': 'flex-direction: row',
  'fdrr': 'flex-direction: row-reverse',
  'ffc': 'flex-direction: column',
  'ffcn': 'flex-flow: column nowrap',
  'ffcr': 'flex-direction: column-reverse',
  'ffcrn': 'flex-flow: column-reverse nowrap',
  'ffcrw': 'flex-flow: column-reverse wrap',
  'ffcrwr': 'flex-flow:column-reverse wrap-reverse',
  'ffcu': 'font-family: cursive',
  'ffcw': 'flex-flow:column wrap',
  'ffcwr': 'flex-flow: column wrap-reverse',
  'fff': 'font-family: fantasy',
  'ffm': 'font-family: monospace',
  'ffn': 'flex-wrap: nowrap',
  'ffr': 'flex-direction: row',
  'ffrn': 'flex-flow:row nowrap',
  'ffrr': 'flex-direction: row-reverse',
  'ffrrn': 'flex-flow: row-reverse nowrap',
  'ffrrw': 'flex-flow:row-reverse wrap',
  'ffrrwr': 'flex-flow: row-reverse wrap-reverse',
  'ffrw': 'flex-flow: row wrap',
  'ffrwr': 'flex-flow:row wrap-reverse',
  'ffs': 'font-family: serif',
  'ffss': 'font-family: sans-serif',
  'ffw': 'flex-flow-wrap: wrap',
  'ffwp': 'flex-flow-wrap: wrap-reverse',
 'fiaa': 'flex-item-align: auto',
  'fiab': 'flex-item-align: baseline',
  'fiac': 'flex-item-align: center',
  'fiae': 'flex-item-align: end',
  'fias2': 'flex-item-align: stretch',
  'fias': 'flex-item-align: start',
  'fias/stretch': 'flex-item-align: stretch',
  'fias/start': 'flex-item-align: start',
  'fiasth': 'flex-item-align: stretch',
 'fka': 'font-kerning: auto',
  'fkn2': 'font-kerning: normal',
  'fkn': 'font-kerning: none',
  'fknl': 'font-kerning: normal',
  'fl': 'float: left',
  'fln': 'filter: none',
  'flpc': 'flex-line-pack: center',
  'flpd': 'flex-line-pack: distribute',
  'flpe': 'flex-line-pack: end',
  'flpj': 'flex-line-pack: justify',
  'flps/stretch': 'flex-line-pack: stretch',
  'flps/start': 'flex-line-pack: start',
  'flpsth': 'flex-line-pack: stretch',
 'fn': 'float: none',
  'fr': 'float: right',
  'fsa': 'font-smooth: auto',
  'fsal': 'font-smooth: always',
  'fsan': 'font-size-adjust: none',
  'fsc': 'font-stretch: condensed',
  'fse': 'font-stretch: expanded',
  'fsec': 'font-stretch: extra-condensed',
  'fsee': 'font-stretch: extra-expanded',
  'fsg': '-moz-osx-font-smoothing:grayscale',
  'fsi': 'font-style: italic',
  'fsi/italic': 'font-style: italic',
  'fsl2': 'font-size: larger',
  'fsl': 'font-size: large',
  'fsl/larger': 'font-size: larger',
  'fsl/large': 'font-size: large',
  'fslr': 'font-size: larger',
  'fsm': 'font-size: medium',
  'fsn2': 'font-style: normal',
  'fsn3': 'font-stretch: normal',
  'fsn4': 'font-smooth: never',
  'fsn/never': 'font-smooth: never',
  'fsn': 'font-synthesis: none',
  'fsnl': 'font-style: normal',
  'fsnml': 'font-stretch: normal',
  'fsnv': 'font-smooth: never',
  'fso': 'font-style: oblique',
 'fss2': 'font-size: smaller',
  'fss': 'font-size: small',
  'fss/smaller': 'font-size: smaller',
  'fss/small': 'font-size: small',
  'fssc': 'font-stretch: semi-condensed',
  'fsse': 'font-stretch: semi-expanded',
  'fssr': 'font-size: smaller',
 'fsuc': 'font-stretch: ultra-condensed',
  'fsue': 'font-stretch: ultra-expanded',
  'fsw': 'font-synthesis: weight',
  'fsws': 'font-synthesis: weight style',
  'fsxl2': 'font-size: xx-large',
  'fsxl': 'font-size: x-large',
  'fsxl/xx': 'font-size: xx-large',
  'fsxl/x': 'font-size: x-large',
  'fsxs2': 'font-size: xx-small',
  'fsxs': 'font-size: x-small',
  
  'fsxxl': 'font-size: xx-large',
  'fsxxs': 'font-size: xx-small',
 'fvapc': 'font-variant: all-petite-caps',
  'fvasc': 'font-variant: all-small-caps',
  'fvcapc': 'font-variant-caps: all-petite-caps',
  'fvcasc': 'font-variant-caps: all-small-caps',
  'fvcn': 'font-variant-caps: normal',
  'fvcnl': 'font-variant-caps: normal',
  'fvcpc': 'font-variant-caps: petite-caps',
  'fvcsc': 'font-variant-caps: small-caps',
  'fvctc': 'font-variant-caps: titling-caps',
  'fvcu': 'font-variant-caps: unicase',
  'fvnl': 'font-variant: normal',
  'fvpc': 'font-variant: petite-caps',
  'fvsc': 'font-variant: small-caps',
  'fvtc': 'font-variant: titling-caps',
  'fvu': 'font-variant: unicase',
  'fw1': 'font-weight: 100',
  'fw2': 'font-weight: 200',
  'fw3': 'font-weight: 300',
  'fw4': 'font-weight: 400',
  'fw5': 'font-weight: 500',
  'fw6': 'font-weight: 600',
  'fw7': 'font-weight: 700',
  'fw8': 'font-weight: 800',
  'fw9': 'font-weight: 900',
  'fwb2': 'font-weight: bolder',
  'fwb': 'font-weight: bold',
  'fwb/bolder': 'font-weight: bolder',
  'fwb/bold': 'font-weight: bold',
  'fwbr': 'font-weight: bolder',
  'fwl': 'font-weight: lighter',
  'fwn2': 'font-weight: normal',
  'fwn': 'flex-wrap: nowrap',
  'fwnl': 'font-weight: normal',
  'fww': 'flex-wrap: wrap',
  'fwwr': 'flex-wrap: wrap-reverse',
  'gaca': 'grid-auto-columns:auto',
  'gacmc': 'grid-auto-columns:min-content',
  'gacxc': 'grid-auto-columns:max-content',
  'gara': 'grid-auto-rows:auto',
  'garmc': 'grid-auto-rows:min-content',
  'garxc': 'grid-auto-rows:max-content',
  'ha2': 'height:auto',
  'ha': 'hyphens: auto',
  'ha/height': 'height:auto',
  'ha/hyphen': 'hyphens: auto',
  'hm': 'hyphens: manual',
  'hmc': 'height:min-content',
  'hn': 'hyphens: none',
  'hpae': 'hanging-punctuation: allow-end',
  'hpf': 'hanging-punctuation: first',
  'hpfae': 'hanging-punctuation: first allow-end',
  'hpfe': 'hanging-punctuation: force-end',
  'hpffe': 'hanging-punctuation: first force-end',
  'hpl': 'hanging-punctuation: last',
  'hplae': 'hanging-punctuation: last allow-end',
  'hplfe': 'hanging-punctuation: last force-end',
  'hpn': 'hanging-punctuation: none',
  'hxc': 'height:max-content',
  'ia': 'icon: auto',
  'ifpf': 'include-font-padding:false',
  'ifpt': 'include-font-padding:true',
  'iof': 'image-orientation: flip',
  'jcc': 'justify-content: center',
  'jce': 'justify-content: end',
  'jcfe': 'justify-content: flex-end',
  'jcfs': 'justify-content: flex-start',
  'jcs': 'justify-content: start',
  'jcsa': 'justify-content: space-around',
  'jcsb': 'justify-content: space-between',
  'jcse': 'justify-content: space-evenly',
  'jib': 'justify-items: baseline',
  'jic': 'justify-items: center',
  'jie': 'justify-items: end',
  'jifb': 'justify-items: first baseline',
  'jife': 'justify-items: flex-end',
  'jifs': 'justify-items: flex-start',
 'jil': 'justify-items: left',
  'jilb': 'justify-items: last baseline',
  'jilc': 'justify-items: legacy center',
  'jill': 'justify-items: legacy left',
  'jilr': 'justify-items: legacy right',
  'jin': 'justify-items: normal',
 'jir': 'justify-items: right',
 'jir/right': 'justify-items: right',
  'jis2': 'justify-items: stretch',
  'jis': 'justify-items: start',
   'jis/stretch': 'justify-items: stretch',
  'jis/start': 'justify-items: start',
  'jisc': 'justify-items: safe center',
  'jise': 'justify-items: self-end',
  'jiss': 'justify-items: self-start',
  'jist': 'justify-items: stretch',
 'jiuc': 'justify-items: unsafe center',
  'jsa': 'justify-self: auto',
  'jsb': 'justify-self: baseline',
  'jsc': 'justify-self: center',
  'jse': 'justify-self: end',
  'jsfb': 'justify-self: first baseline',
  'jsfe': 'justify-self: flex-end',
  'jsfs': 'justify-self: flex-start',
  'jsl': 'justify-self: left',
  'jslb': 'justify-self: last baseline',
  'jsn': 'justify-self: normal',
 'jsr': 'justify-self: right',
 'jsr/right': 'justify-self: right',
  'jss2': 'justify-self: stretch',
  'jss': 'justify-self: start',
  'jss/stretch': 'justify-self: stretch',
  'jss/start': 'justify-self: start',
  'jssc': 'justify-self: safe center',
  'jsse': 'justify-self: self-end',
  'jsss': 'justify-self: self-start',
  'jsst': 'justify-self: stretch',
 'jsuc': 'justify-self: unsafe center',
  'la': 'left: auto',
  'lba': 'line-break: auto',
  'lbl': 'line-break: loose',
  'lbn': 'line-break: normal',
  'lbnl': 'line-break: normal',
  'lbs': 'line-break: strict',
  'lesnl': 'letter-spacing: normal',
 'lhn': 'line-height: normal',
  'lhnl': 'line-height: normal',
  'lsa': 'list-style-type: armenian',
  'lsc': 'list-style-type: circle',
  'lsd2': 'list-style-type: decimal',
  'lsd': 'list-style-type: disc',
  'lsd/decimal': 'list-style-type: decimal',
  'lsd/disc': 'list-style-type: disc',
  'lsdc': 'list-style-type: decimal',
  'lsdlz': 'list-style-type: decimal-leading-zero',
  'lsg': 'list-style-type: georgian',
  'lsin': 'list-style-image: none',
  'lsla': 'list-style-type: lower-alpha',
  'lslg': 'list-style-type: lower-greek',
  'lsll': 'list-style-type: lower-latin',
  'lslr': 'list-style-type: lower-roman',
  'lsn2': 'letter-spacing: normal',
  'lsn': 'list-style: none',
  'lsn/normal': 'letter-spacing: normal',
  'lsn/none': 'list-style: none',
  'lsnl': 'letter-spacing: normal',
  'lspi': 'list-style-position: inside',
  'lspo': 'list-style-position: outside',
  'lss': 'list-style-type: square',
  'lsta': 'list-style-type: armenian',
  'lstc': 'list-style-type: circle',
  'lstd2': 'list-style-type: decimal',
  'lstd': 'list-style-type: disc',
   'lstd/decimal': 'list-style-type: decimal',
  'lstd/disc': 'list-style-type: disc',
  'lstdlz': 'list-style-type: decimal-leading-zero',
  'lstg': 'list-style-type: georgian',
  'lstla': 'list-style-type: lower-alpha',
  'lstlg': 'list-style-type: lower-greek',
  'lstll': 'list-style-type: lower-latin',
  'lstlr': 'list-style-type: lower-roman',
  'lstn': 'list-style-type: none',
  'lsts': 'list-style-type: square',
  'lstua': 'list-style-type: upper-alpha',
  'lstul': 'list-style-type: upper-latin',
  'lstur': 'list-style-type: upper-roman',
  'lsua': 'list-style-type: upper-alpha',
  'lsul': 'list-style-type: upper-latin',
  'lsur': 'list-style-type: upper-roman',
  'ma': 'margin:auto',
  'maa': 'margin:auto auto',
  'mba': 'margin-bottom: auto',
  'mbmc': 'mix-blend-mode: color',
  'mbmcb': 'mix-blend-mode: color-burn',
  'mbmcd': 'mix-blend-mode: color-dodge',
  'mbmd2': 'mix-blend-mode: difference',
  'mbmd': 'mix-blend-mode: darken',
  'mbmd/difference': 'mix-blend-mode: difference',
  'mbmd/darken': 'mix-blend-mode: darken',
  'mbmdf': 'mix-blend-mode: difference',
  'mbme': 'mix-blend-mode: exclusion',
  'mbmh': 'mix-blend-mode: hue',
  'mbml2': 'mix-blend-mode: luminosity',
  'mbml': 'mix-blend-mode: lighten',
  'mbml/luminisity': 'mix-blend-mode: luminosity',
  'mbml/lighten': 'mix-blend-mode: lighten',
  'mbmlu': 'mix-blend-mode: luminosity',
  'mbmm': 'mix-blend-mode: multiply',
  'mbmn': 'mix-blend-mode: normal',
  'mbmo': 'mix-blend-mode: overlay',
  'mbms2': 'mix-blend-mode: saturation',
  'mbms': 'mix-blend-mode: screen',
   'mbms/saturation': 'mix-blend-mode: saturation',
  'mbms/screen': 'mix-blend-mode: screen',
  'mbmsa': 'mix-blend-mode: saturation',
  'mha': 'min-height: auto',
  'mla': 'margin-left: auto',
  'mma': 'mask-mode:alpha',
 'mml': 'mask-mode:luminance',
  'mmms': 'mask-mode:match-source',
  'mobb': 'mask-origin: border-box',
  'mocb': 'mask-origin: content-box',
  'mofb': 'mask-origin: fill-box',
  'mopb': 'mask-origin: padding-box',
  'mosb': 'mask-origin: stroke-box',
  'movb': 'mask-origin: view-box',
  'mra': 'margin-right: auto',
  'mrnr': 'mask-repeat: no-repeat',
  'mrr2': 'mask-repeat: round',
  'mrr': 'mask-repeat: repeat',
   'mrr/round': 'mask-repeat: round',
  'mrr/repeat': 'mask-repeat: repeat',
  'mrro': 'mask-repeat: round',
  'mrrx': 'mask-repeat: repeat-x',
  'mrry': 'mask-repeat: repeat-y',
  'mrs': 'mask-repeat: space',
  'mta': 'margin-top: auto',
  'mwa': 'min-width: auto',
  'oa': 'overflow: auto',
  'oba': 'overscroll-behavior: auto',
  'obac': 'overscroll-behavior: auto contain',
  'oban': 'overscroll-behavior: auto none',
  'obba': 'overscroll-behavior-block: auto',
  'obbc': 'overscroll-behavior-block: contain',
  'obbn': 'overscroll-behavior-block: none',
 'obc': 'overscroll-behavior: contain',
  'obca': 'overscroll-behavior: contain auto',
  'obcn': 'overscroll-behavior: contain none',
  'obia': 'overscroll-behavior-inline: auto',
  'obic': 'overscroll-behavior-inline: contain',
 'obin': 'overscroll-behavior-inline: none',
  'obn': 'overscroll-behavior: none',
  'obna': 'overscroll-behavior: none auto',
  'obnc': 'overscroll-behavior: none contain',
 'obxa': 'overscroll-behavior-x: auto',
  'obxc': 'overscroll-behavior-x: contain',
 'obxn': 'overscroll-behavior-x: none',
 'obya': 'overscroll-behavior-y: auto',
  'obyc': 'overscroll-behavior-y: contain',
 'obyn': 'overscroll-behavior-y: none',
 'ofc': 'object-fit: cover',
  'ofcon': 'object-fit: contain',
  'off': 'object-fit: fill',
  'ofn': 'object-fit: none',
  'ofsd': 'object-fit: scale-down',
  'oh': 'overflow: hidden',
  'oln': 'outline:none',
  'on': 'outline:none',
  'opcc': 'object-position: center center',
  'oplt': 'object-position: left top',
  'oprb': 'object-position: right bottom',
 'os': 'overflow: scroll',
  'osa': 'outline-style: auto',
  'osd2': 'outline-style: double',
  'osd3': 'outline-style: dotted',
  'osd': 'outline-style: dashed',
  'osd/double': 'outline-style: double',
  'osd/dotted': 'outline-style: dotted',
  'osd/dashed': 'outline-style: dashed',
  'osdb': 'outline-style: double',
  'osds': 'outline-style: dashed',
  'osdt': 'outline-style: dotted',
  'osg': 'outline-style: groove',
  'osi': 'outline-style: inset',
  'osn': 'outline-style: none',
  'oso': 'outline-style: outset',
  'osr': 'outline-style: ridge',
  'oss': 'outline-style: solid',
  'ov': 'overflow: visible',
  'owbw': 'overflow-wrap: break-word',
  'owm': 'outline-width: medium',
  'own': 'overflow-wrap: normal',
  'ownl': 'overflow-wrap: normal',
  'owt2': 'outline-width: thin',
  'owt': 'outline-width: thick',
  'owt/thin': 'outline-width: thin',
  'owt/thick': 'outline-width: thick',
  'owtn': 'outline-width: thin',
  'owww': 'overflow-wrap: word-wrap',
  'oxa': 'overflow-x: auto',
  'oxh': 'overflow-x: hidden',
  'oxs': 'overflow-x: scroll',
  'oxv': 'overflow-x: visible',
  'oya': 'overflow-y: auto',
  'oyh': 'overflow-y: hidden',
  'oys': 'overflow-y: scroll',
  'oyv': 'overflow-y: visible',
  'pa': 'position: absolute',
  'pbaa2': 'page-break-after: avoid',
  'pbaa3': 'page-break-after: always',
  'pbaa': 'page-break-after: auto',
  'pbaa/avoid': 'page-break-after: avoid',
  'pbaa/always': 'page-break-after: always',
  'pbaa/auto': 'page-break-after: auto',
  'pbaal': 'page-break-after: always',
  'pbaav': 'page-break-after: avoid',
  'pbal': 'page-break-after: left',
  'pbar': 'page-break-after: right',
  'pbba2': 'page-break-before: avoid',
  'pbba3': 'page-break-before: always',
  'pbba': 'page-break-before: auto',
  'pbba/avoid': 'page-break-before: avoid',
  'pbba/always': 'page-break-before: always',
  'pbba/auto': 'page-break-before: auto',
  'pbbal': 'page-break-before: always',
  'pbbav': 'page-break-before: avoid',
  'pbbl': 'page-break-before: left',
  'pbbr': 'page-break-before: right',
  'pbia2': 'page-break-inside: avoid',
  'pbia': 'page-break-inside: auto',
  'pbiav': 'page-break-inside: avoid',
  'pc': 'position: center',
  'pcbc': 'place-content: baseline center',
  'pccs': 'place-content: center start',
  'pcel': 'place-content: end left',
  'pcfbse': 'place-content: first baseline space-evenly',
  'pcfec': 'place-content: flex-end center',
  'pcfsc': 'place-content: flex-start center',
  'pclbr': 'place-content: last baseline right',
  'pcsase': 'place-content: space-around space-evenly',
  'pcsbse': 'place-content: space-between space-evenly',
  'pcsc': 'place-content: start center',
  'pcses': 'place-content: space-evenly stretch',
  'pcsse': 'place-content: stretch space-evenly',
 'pea': 'pointer-events: auto',
  'pen': 'pointer-events: none',
  'pf': 'position: fixed',
 'pibn': 'place-items: baseline normal',
  'pic': 'place-items: center',
  'picn': 'place-items: center normal',
  'pien': 'place-items: end normal',
  'pifbl': 'place-items: first baseline legacy',
  'pifen': 'place-items: flex-end normal',
  'pifsl': 'place-items: flex-start legacy',
  'pilbn': 'place-items: last baseline normal',
 'pins': 'place-items: normal start',
  'pisen': 'place-items: self-end normal',
  'pisl2': 'place-items: stretch legacy',
  'pisl': 'place-items: start legacy',
  'pisl/stretch': 'place-items: stretch legacy',
  'pisl/start': 'place-items: start legacy',
  'pissl': 'place-items: self-start legacy',
  'pistl': 'place-items: stretch legacy',
 'pn': 'perspective: none',
  'pob': 'perspective-origin: bottom',
  'pobl': 'perspective-origin: bottom left',
  'pobr': 'perspective-origin: bottom right',
  'pobtm': 'perspective-origin: bottom',
  'poc': 'perspective-origin: center',
  'pol': 'perspective-origin: left',
  'por': 'perspective-origin: right',
  'pot': 'perspective-origin: top',
  'potl': 'perspective-origin: top left',
  'potr': 'perspective-origin: top right',
  'pp': 'position: page',
  'pr': 'position: relative',
  'ps2': 'position: sticky',
  'ps': 'position: static',
  'ps/sticky': 'position: sticky',
  'ps/static': 'position: static',
  'psac': 'place-self: auto center',
  'psbn': 'place-self: baseline normal',
  'pscn': 'place-self: center normal',
  'psen': 'place-self: end normal',
  'psfba': 'place-self: first baseline auto',
  'psfen': 'place-self: flex-end normal',
  'psfsa': 'place-self: flex-start auto',
 'pslbn': 'place-self: last baseline normal',
  'psns': 'place-self: normal start',
  'pssa2': 'place-self: stretch auto',
  'pssa': 'place-self: start auto',
  'pssa/stretch': 'place-self: stretch auto',
  'pssa/start': 'place-self: start auto',
  'pssen': 'place-self: self-end normal',
  'psssa': 'place-self: self-start auto',
  'pssta': 'place-self: stretch auto',
  'pst': 'position: sticky',
 'qn': 'quotes: none',
  'ra': 'right: auto',
  'rb': 'resize: both',
  'rh': 'resize: horizontal',
  'rv': 'resize: vertical',
  'sba': 'scroll-behavior:auto',
  'sb-inherit': 'scroll-behavior:inherit',
  'sb-initial': 'scroll-behavior:initial',
  'sbs': 'scroll-behavior:smooth',
  'sla': 'stroke-linejoin:arcs',
  'slb2': 'stroke-linejoin:bevel',
  'slb': 'stroke-linecap:butt',
  'slb/bevel': 'stroke-linejoin:bevel',
  'slb/butt': 'stroke-linecap:butt',
  'slcb': 'stroke-linecap:butt',
  'slcr': 'stroke-linecap:round',
  'slcs': 'stroke-linecap:square',
  'slja': 'stroke-linejoin:arcs',
  'sljb': 'stroke-linejoin:bevel',
  'sljm': 'stroke-linejoin:milter',
  'sljmc': 'stroke-linejoin:milter-clip',
  'sljr': 'stroke-linejoin:round',
  'slm': 'stroke-linejoin:milter',
  'slmc': 'stroke-linejoin:milter-clip',
  'slr2': 'stroke-linejoin:round',
  'slr': 'stroke-linecap:round',
  'slr/linejoin': 'stroke-linejoin:round',
  'slr/linecap': 'stroke-linecap:round',
  'slr/join': 'stroke-linejoin:round',
  'slr/cap': 'stroke-linecap:round',
  'sls': 'stroke-linecap:square',
  'ta': 'top: auto',
  'tac': 'text-align: center',
  'tae': 'text-align: end',
 'taj': 'text-align: justify',
  'tal': 'text-align: left',
  'tala': 'text-align-last: auto',
  'talc': 'text-align-last: center',
  'tale': 'text-align-last: end',
  'talj': 'text-align-last: justify',
  'tall': 'text-align-last: left',
  'talr': 'text-align-last: right',
  'tals': 'text-align-last: start',
  'tamp': 'text-align: match-parent',
  'tar': 'text-align: right',
  'tas': 'text-align: start',
  'tase': 'text-align: start end',
  'tava': 'text-align-vertical:auto',
  'tavb': 'text-align-vertical:bottom',
  'tavc': 'text-align-vertical:center',
  'tavt': 'text-align-vertical:top',
  'tcha': 'text-combine-horizontal: all',
  'tchd': 'text-combine-horizontal: digits ',
  'tchn': 'text-combine-horizontal: none',
  'tdb': 'text-decoration: blink',
  'tdd2': 'text-decoration: double',
  'tdd3': 'text-decoration: dotted',
  'tdd': 'text-decoration: dashed',
  'tdd/double': 'text-decoration: double',
  'tdd/dotted': 'text-decoration: dotted',
  'tdd/dashed': 'text-decoration: dashed',
  'tddb': 'text-decoration: double',
  'tdds': 'text-decoration: dashed',
  'tddt': 'text-decoration: dotted',
 'tdin': 'text-decoration:inherit ',
  'tdlb': 'text-decoration-line: blink',
 'tdllt': 'text-decoration-line: line-through',
  'tdln': 'text-decoration-line: none',
  'tdlo': 'text-decoration: overline',
  'tdlt': 'text-decoration: line-through',
  'tdlu': 'text-decoration-line: underline',
  'tdlult': 'text-decoration-line: underline line-through',
  'tdn': 'text-decoration: none',
  'tdo': 'text-decoration: overline',
  'tdsbd': 'text-decoration-skip: box-decoration',
  'tdsd2': 'text-decoration-style: dashed',
  'tdsd3': 'text-decoration-style: dotted',
  'tdsd': 'text-decoration-style: double',
   'tdsd/double': 'text-decoration-style: dashed',
  'tdsd/dotted': 'text-decoration-style: dotted',
  'tdsd/dashed': 'text-decoration-style: double',
  'tdsdb': 'text-decoration-style: double',
  'tdsds': 'text-decoration-style: dashed',
  'tdsdt': 'text-decoration-style: dotted',
  'tdse': 'text-decoration-skip: edges',
  'tdsi': 'text-decoration-skip: ink',
  'tdsn': 'text-decoration-skip: none',
  'tdso': 'text-decoration-skip: objects',
  'tdss': 'text-decoration-style: solid',
  'tdssp': 'text-decoration-skip: spaces',
  'tdsw': 'text-decoration-style: wavy',
  'tdu': 'text-decoration: underline',
  'tdw': 'text-decoration: wavy',
  'tepbl': 'text-emphasis-position: below left',
  'tepbr': 'text-emphasis-position: below right',
  'tepol': 'text-emphasis-position: over left',
  'tepor': 'text-emphasis-position: over right',
  'tesc': 'text-emphasis-style: circle',
  'tesd': 'text-emphasis-style: dot',
  'tesdc': 'text-emphasis-style: double-circle',
  'tesf': 'text-emphasis-style: filled',
  'tesn': 'text-emphasis-style: none',
  'teso': 'text-emphasis-style: open',
  'tess': 'text-emphasis-style: sesame',
  'test': 'text-emphasis-style: triangle',
  'tetep': 'text-emphasis: text-emphasis-position',
  'tiel': 'text-indent: each-line',
  'tih': 'text-indent: hanging',
  'tja': 'text-justify: auto',
  'tjd': 'text-justify: distribute',
  'tjiw': 'text-justify: inter-word',
  'tjn': 'text-justify: none',
  'tla': 'table-layout: auto',
  'tlf': 'table-layout: fixed',
  'tn': 'transform: none',
  'tob': 'transform-origin: bottom',
  'tobc': 'transform-origin: bottom center  ',
  'tobl': 'transform-origin: bottom left  ',
  'tobr': 'transform-origin: bottom right  ',
  'tobtm': 'transform-origin: bottom',
  'toc2': 'text-overflow: clip',
  'toc': 'transform-origin: center',
   'toc/clip': 'text-overflow: clip',
  'toc/center': 'transform-origin: center',
  'toc/text': 'text-overflow: clip',
  'toc/transform': 'transform-origin: center',
  'toc/overflow': 'text-overflow: clip',
  'toc/origin': 'transform-origin: center',
  'tocb': 'transform-origin: center  bottom',
  'tocc': 'transform-origin: center  center',
  'tocl': 'transform-origin: center  left',
  'tocr': 'transform-origin: center  right',
  'toct': 'transform-origin: center  top',
  'toe': 'text-overflow: ellipsis',
  'tol': 'transform-origin: left',
  'tolb': 'transform-origin: left bottom',
  'tolc': 'transform-origin: left center',
  'tolt': 'transform-origin: left top',
  'tom': 'text-orientation: mixed',
  'tor': 'transform-origin: right',
  'torb': 'transform-origin: right  bottom',
  'torc': 'transform-origin: right  center',
  'tort': 'transform-origin: right  top',
  'tos': 'text-orientation: sideways',
  'tosl': 'text-orientation: sideways-left',
  'tosr': 'text-orientation: sideways-right',
  'tot': 'transform-origin: top',
  'totc': 'transform-origin: top center  ',
  'totl': 'transform-origin: top left  ',
  'totr': 'transform-origin: top right  ',
  'tou': 'text-orientation: upright',
  'tougo': 'text-orientation: use-glyph-orientation',
  'tpa': 'transition-property: all',
  'tpb': 'transition-property: background',
  'tpc': 'transition-property: color',
  'tpn': 'transition-property: none',
  'tpt': 'transition-property: transform',
  'tra': 'text-rendering: auto',
  'trg': 'text-rendering: geometricPrecision',
  'trgp': 'text-rendering: geometricPrecision',
  'tro2': 'text-rendering: optimizeSpeed',
  'tro': 'text-rendering: optimizeLegibility',
  'trop': 'text-rendering: optimizeLegibility',
  'tros': 'text-rendering: optimizeSpeed',
  'tsf': 'transform-style: flat',
  'tsn': 'text-shadow: none',
  'tsp3': 'transform-style: preserve-3d',
  'tsp3d': 'transform-style: preserve-3d',
  'ttc': 'text-transform: capitalize',
  'ttfe': 'transition-timing-function: ease',
  'ttfei': 'transition-timing-function: ease-in',
  'ttfeio': 'transition-timing-function: ease-in-out',
  'ttfeo': 'transition-timing-function: ease-out',
  'ttfl': 'transition-timing-function: linear',
  'ttfse': 'transition-timing-function: step-end',
  'ttfss': 'transition-timing-function: step-start',
  'ttfw': 'text-transform: full-width',
  'ttl': 'text-transform: lowercase',
  'ttn': 'text-transform: none',
  'ttu': 'text-transform: uppercase',
  'tupa': 'text-underline-position: auto',
  'tupl': 'text-underline-position: left',
  'tupr': 'text-underline-position: right',
  'tupu': 'text-underline-position: under',
  'tupul': 'text-underline-position: under left',
  'tupur': 'text-underline-position: under right',
  'ubbo': 'unicode-bidi: bidi-override',
  'ube': 'unicode-bidi: embed',
  'ubn': 'unicode-bidi: normal',
  'ubnl': 'unicode-bidi: normal',
  'usa2': 'user-select: all',
  'usa': 'user-select: auto',
  'usa/all': 'user-select: all',
  'usa/auto': 'user-select: auto',
  'usal': 'user-select: all',
  'usc': 'user-select: contain',
 'usn': 'user-select: none',
 'ust': 'user-select: text',
 'vab2': 'vertical-align: bottom',
  'vab': 'vertical-align: baseline',
  'vab/bottom': 'vertical-align: bottom',
  'vab/baseline': 'vertical-align: baseline',
  'vabtm': 'vertical-align: bottom',
  'vam': 'vertical-align: middle',
  'vas': 'vertical-align: super',
  'vasb': 'vertical-align: sub',
  'vat': 'vertical-align: top',
  'vatb': 'vertical-align: text-bottom',
  'vatt': 'vertical-align: text-top',
  'vc': 'visibility: collapse',
  'vh': 'visibility: hidden',
  'vv': 'visibility: visible',
  'wa': 'width: auto',
  'wbba': 'word-break: break-all',
  'wbbw': 'word-break: break-word',
  'wbka': 'word-break: keep-all',
  'wbn': 'word-break: normal',
  'wbnl': 'word-break: normal',
  'wda': 'writing-direction-auto',
  'wdl': 'writing-direction-ltr',
  'wdltr': 'writing-direction-ltr',
  'wdr': 'writing-direction-rtl',
  'wdrtl': 'writing-direction-rtl',
  'wkmma': '-webkit-mask-mode:alpha',
 'wkmml': '-webkit-mask-mode:luminance',
  'wkmmms': '-webkit-mask-mode:match-source',
  'wkmobb': '-webkit-mask-origin: border-box',
  'wkmocb': '-webkit-mask-origin: content-box',
  'wkmofb': '-webkit-mask-origin: fill-box',
  'wkmopb': '-webkit-mask-origin: padding-box',
  'wkmosb': '-webkit-mask-origin: stroke-box',
  'wkmovb': '-webkit-mask-origin: view-box',
  'wmc': 'width:min-content',
  'wmht': 'writing-mode: horizontal-tb',
  'wmvl': 'writing-mode: vertical-lr',
  'wmvlr': 'writing-mode: vertical-lr',
  'wmvr': 'writing-mode: vertical-rl',
  'wmvrl': 'writing-mode: vertical-rl',
  'wosnl': 'word-spacing: normal',
  'wsn2': 'white-space: normal',
  'wsn3': 'word-spacing:normal',
  'wsn': 'white-space: nowrap',
   'wsn/space': 'white-space: normal',
   'wsn/white': 'white-space: normal',
  'wsn/world': 'word-spacing:normal',
  'wsn/spacing': 'word-spacing:normal',
  'wsn/nowrap': 'white-space: nowrap',
  'wsnl': 'white-space: normal',
  'wsnw': 'white-space: nowarp',
  'wsp': 'white-space: pre',
  'wspl': 'white-space: pre-line',
  'wspw': 'white-space: pre-wrap',
  'wwbw': 'word-wrap: break-word',
  'wwn': 'word-wrap: normal',
  'wwnl': 'word-wrap: normal',
  'wwow': 'word-wrap: overflow-wrap',
  'wxc': 'width:max-content',
  'xhn': 'max-height: none',
  'xwn': 'max-width: none',
  'zia': 'z-index: auto',
};
 
  
  
  
  
 